### ISSUE TITLE
Missing required module 'RazorpayCommonCrypto'

### ISSUE THREAD

**Issue by rkpradeep20** [razorpay/razorpay-pod#10]
I keep getting this exception every time I import razorpay into my swift view controller. I'm using cocoapods with razorpay-pod version 1.0.14. Please help. Need a fix for it at the earliest. 

Thanks.

**Comment by rkpradeep20** [comment]
I'm using Xcode Version 9.3 (9E145).

**Comment by rkpradeep20** [comment]
This is seriously strange. Earlier when I tried to build the app, it kept throwing the exception - Missing required module 'RazorpayCommonCrypto'. I have been trying a fix since afternoon. I gave up after not getting any solution and that's when I posted an issue, I usually don't post any issue unless I really need help. But now it's suddenly working. I had cleaned, removed all pod file and once again cleaned, and done a number of things to make it work. But now its magically just working. 

I'm sorry and thanks for replying so quickly.

**Comment by iThink32** [comment]
its alright , but if its working now it means that you've done something to make it work.I believe there is something that you still must look into , nonetheless I've checked from my end and it works fine , closing this issue for now , reopen it if you face any issue.

**Comment by iThink32** [comment]
hey have you used CommonCrypto in your project by any chance?

**Comment by rkpradeep20** [comment]
Sorry for the late replay. I’m not using CommonCrypto.
I think I figured out how I resolved the issue. I had commented out everything to do with razorpay and then run the project. Following that I Uncommented razorpay part that was commented. Probably doing that resolved the issue.
