### ISSUE TITLE
Cannot pull the keyboard panel

### ISSUE THREAD

**Issue by cocoadogs** [razorpay/razorpay-pod#102]
## Description

when I call razopay sdk open in my controller, it can't pull up the keyboard panel unless I click the Country input button.But it isn't always be that, sometimes it's ok but it often so bad

## Razorpay pod Version :

1.1.6

## Xcode Version :
Xcode 11.6 (11E708)

### What you did:

self.razorpay = [RazorpayCheckout initWithKey:kRazorpayKeyID andDelegateWithData:self];
                    [self.razorpay open:self.viewModel.razorpayModel displayController:self.navigationController];

or:

self.razorpay = [RazorpayCheckout initWithKey:kRazorpayKeyID andDelegateWithData:self];
                    [self.razorpay open:self.viewModel.razorpayModel displayController:self];

### What happened:

[http://note.youdao.com/s/ZxMqxqX5](bug vedio)

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.
2.

## Code example, screenshot, or link to a repository:
Please provide a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by gourabghosh1** [comment]
@cocoadogs can you share your Mobile device model name and manufacture date and the OS details ?

**Comment by cocoadogs** [comment]
iPhone 6s - iOS 14.0

**Comment by cocoadogs** [comment]
iPhone 6s - iOS 14.0  @gourabghosh1

**Comment by gourabghosh1** [comment]
@cocoadogs our tech team will be fixing this , this may take some time , we recommend you to use pre-fills the contact details for now.

--checkout code--
"prefill": [
                	"contact": "9797979797",
                	"email": "foo@bar.com"
                ],

**Comment by cocoadogs** [comment]
it seems like that the bug is reported only in ios14 beta version.now we don't have seen that again

**Comment by Nautiyalsachin** [comment]
@cocoadogs, well in that case closing this issue now, feel free to either re-open or create a new issue if you have any additional queries.
