### ISSUE TITLE
'Razorpay' is unavailable: cannot find Swift declaration for this class (Xcode 11.6)

### ISSUE THREAD

**Issue by MuthurajMuthulingam** [razorpay/razorpay-pod#103]
- [ ] I have gone through the README.(https://github.com/razorpay/razorpay-pod)
- [ ] I have searched for a similar issue (https://github.com/razorpay/razorpay-pod/issues)
- [ ] I am using the latest version of our framework (https://github.com/razorpay/razorpay-pod/releases)
- [ ] I am gone through the FAQ's (https://github.com/razorpay/razorpay-pod/wiki/FAQ's)
- [ ] I have cleaned my project , deleted derived data and rebuilt it.

**Comment by AYAN249** [comment]
@MuthurajMuthulingam 

It has been finally allowed in Swift 5.3. See Contextual Where Clauses in the official Language Guide.
Citing from there:
You can write a generic where clause as part of a declaration that doesn’t have its own generic type constraints when you’re already working in the context of generic types. For example, you can write a generic where clause on a subscript of a generic type or on a method in an extension to a generic type.
...
extension Container {
    func average() -> Double where Item == Int {
        var sum = 0.0
        for index in 0..<count {
            sum += Double(self[index])
        }
        return sum / Double(count)
    }

That compiles just fine in Xcode 12 beta 4, but won't work in Xcode 11.6 that is shipped with Swift 5.2.4.
See Contextual Where Clauses in the official Language Guide: https://docs.swift.org/swift-book/LanguageGuide/Generics.html#ID628

**Comment by Nautiyalsachin** [comment]
Please change Razorpay to RazorpayCheckout, this will fix this issue, 

Closing this issue now, feel free to either re-open or create a new issue if you have any additional queries.
