### ISSUE TITLE
blank white page on razorpay.open

### ISSUE THREAD

**Issue by karthikxcel** [razorpay/razorpay-pod#106]
## Description
On razorpay.open, only a blank white page appears.

## Razorpay pod Version :
pod 'razorpay-pod', '1.1.7'

## Xcode Version :
Version 11.6 (11E708)

### What you did:
I m calling  razorpay.open method to open the payment page

### What happened:
Instead of the razorpay payment UI, I m getting blank white screen

**Comment by Sumit738** [comment]
Please share the crash log for further investigation.

**Comment by Sumit738** [comment]
Please refer the below link for the sample app https://razorpay.com/docs/payment-gateway/ios-integration/standard/#razorpay-sample-app

**Comment by karthikxcel** [comment]
I m getting Log like this when it fails to load. Sometimes if the UI loads successfully i don't get the below log

2020-09-20 21:31:19.132105+0530 CricDost[335:12225] WF: _userSettingsForUser mobile: {
    filterBlacklist =     (
    );
    filterWhitelist =     (
    );
    restrictWeb = 1;
    useContentFilter = 0;
    useContentFilterOverrides = 0;
    whitelistEnabled = 0;
}
2020-09-20 21:31:19.132181+0530 CricDost[335:12225] WF: _WebFilterIsActive returning: NO

**Comment by karthikxcel** [comment]
I m getting Log like this when it fails to load. Sometimes if the UI loads successfully i don't get the below log

2020-09-20 21:31:19.132105+0530 [335:12225] WF: _userSettingsForUser mobile: {
filterBlacklist = (
);
filterWhitelist = (
);
restrictWeb = 1;
useContentFilter = 0;
useContentFilterOverrides = 0;
whitelistEnabled = 0;
}
2020-09-20 21:31:19.132181+0530 [335:12225] WF: _WebFilterIsActive returning: NO

**Comment by karthikxcel** [comment]
Any update on this issue

**Comment by Nautiyalsachin** [comment]
@karthikxcel, This issue is fixed a long ago, we show a blue activity indicator whenever you call open().  You can try to see its working on this [example](https://github.com/razorpay/razorpay-pod/tree/master/Example). Let me know if you still face any issue.

**Comment by karthikxcel** [comment]
Thank You @Nautiyalsachin. Issue didn't appear again

**Comment by Nautiyalsachin** [comment]
Closing this issue now 😊.
