### ISSUE TITLE
I got crash report using razorpay-pod v1.1.7 

### ISSUE THREAD

**Issue by cocoadogs** [razorpay/razorpay-pod#107]
- [x] I have gone through the README.(https://github.com/razorpay/razorpay-pod)
- [x] I have searched for a similar issue (https://github.com/razorpay/razorpay-pod/issues)
- [x] I am using the latest version of our framework (https://github.com/razorpay/razorpay-pod/releases)
- [x] I am gone through the FAQ's (https://github.com/razorpay/razorpay-pod/wiki/FAQ's)
- [x] I have cleaned my project , deleted derived data and rebuilt it.

com.apple.root.user-initiated-qos

EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000000
$s8Razorpay10LumberjackC10trackEvent9eventName16havingPropertiesySS_SDySSypGtF
keyboard_arrow_down

libswiftCore.dylib
swift_isUniquelyReferenced_nonNull_native + 34

## IDE Specs

Xcode 12 razorpay-pop v1.1.7

## Retro Steps

0
libswiftCore.dylib
swift_isUniquelyReferenced_nonNull_native + 34
arrow_right 1
Razorpay
$s8Razorpay10LumberjackC10trackEvent9eventName16havingPropertiesySS_SDySSypGtF + 592
2
Razorpay
$s8Razorpay13AnalyticsUtilC11reportError_11havingLevel16andCustomMessageySo7NSErrorCSg_AA0aeG0OSStF + 1608
3
Razorpay
$s8Razorpay25FileHandlingUtilFunctionsC08readFromB13AtDefaultPathyS2SFZTf4nd_n + 608
4
Razorpay
$s8Razorpay13CrashReporterC012reportStoredB4Dump33_E1A96831138ED3F3E0A51B461F187E33LLyyFyycfU_ + 56
5
Razorpay
$sIeg_IeyB_TR + 28
6
libdispatch.dylib
_dispatch_call_block_and_release + 24
7
libdispatch.dylib
_dispatch_client_callout + 16
8
libdispatch.dylib
_dispatch_root_queue_drain + 640
9
libdispatch.dylib
_dispatch_worker_thread2 + 112
10
libsystem_pthread.dylib
_pthread_wqthread + 212
11
libsystem_pthread.dylib
start_wqthread + 8

**Comment by cocoadogs** [comment]
here is the firebase crash report image
[http://note.youdao.com/yws/public/resource/d105580302e05a6f002f9b9767d80589/xmlnote/WEBRESOURCE6283791b00169afcfcf390f99523c3f2/15653](razorpay-pod v1.1.7)

**Comment by Nautiyalsachin** [comment]
Hey @cocoadogs, we have released a new Razorpay Pod version `razorpay-pod  v1.1.10`, please try it and let me know if the crash is still happening for you. Closing the issue now.
