### ISSUE TITLE
Failed to build module 'Razorpay' from its module interface

### ISSUE THREAD

**Issue by akshaybhange** [razorpay/razorpay-pod#109]
## Description
Build failed with the following errors:
`failed to build module 'Razorpay' from its module interface; the compiler that produced it, 'Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)'`
and
`<unknown>:0: error: unable to load standard library for target 'arm64-apple-ios10.0'`

## Razorpay pod Version :
    pod 'razorpay-pod', '1.1.7'

## Xcode Version :
    Version 12.0.1 (12A7300)

### What you did:
I was working on our code which was earlier build on xcode 10 and razorpay pod was 1.1.1. With xcode 12 it was failing so I updated rayzorpay-pod 1.1.7

followed instruction given in the [documentation](https://razorpay.com/docs/payment-gateway/ios-integration/standard/#cocoapod) 
changed `var razorpay: Razorpay!` to `var razorpay: RazorpayCheckout!`
and initWithKey function as well

### What happened:

<img width="874" alt="Screenshot 2020-10-09 at 9 06 15 PM" src="https://user-images.githubusercontent.com/39375914/95603048-6364cf80-0a73-11eb-802c-84bc81fe4060.png">

**Comment by ankit0812** [comment]
Did you manage to solve this?

**Comment by SandyAra** [comment]
Same issue for me too. solved this ?

**Comment by akshaybhange** [comment]
not yet. I opened a SO query and received an answer there. Hope that will help. I didn't tried yet.

[https://stackoverflow.com/questions/64373197/failed-to-build-module-razorpay-from-its-module-interface/64550071#64550071](https://stackoverflow.com/questions/64373197/failed-to-build-module-razorpay-from-its-module-interface/64550071#64550071)

**Comment by Nautiyalsachin** [comment]
Hey @akshaybhange, i am working on this release as you can see on GitHub releases. This release will be available soon.

**Comment by akshaybhange** [comment]
@Nautiyalsachin, Sorry to disturb you. any estimated release date for pod v1.1.9?

**Comment by Nautiyalsachin** [comment]
Hi everyone, we have released a new pod version. 

Please update it to the latest version -  `pod 'razorpay-pod', '1.1.10'`.

Let me know if this works for you.

**Comment by manojpocket52** [comment]
failed to build module 'Razorpay' from its module interface; the compiler that produced it, 'Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)'

**Comment by Nautiyalsachin** [comment]
Hey @manojpocket52, Xcode is having some issues with module stability, we have to release a new build for this, and this can take a little more time. For now, I would suggest you to downgrade your Xcode and use it so that this issue won't effect you.

**Comment by navya15-ios** [comment]
> failed to build module 'Razorpay' from its module interface; the compiler that produced it, 'Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)'

Any solution for this?

**Comment by navya15-ios** [comment]
> Hey @manojpocket52, Xcode is having some issues with module stability, we have to release a new build for this, and this can take a little more time. For now, I would suggest you to downgrade your Xcode and use it so that this issue won't effect you

> failed to build module 'Razorpay' from its module interface; the compiler that produced it, 'Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)'

@manojpocket52 @Nautiyalsachin  Any solution for this issue?

**Comment by Nautiyalsachin** [comment]
Hey @navya15-ios: Please update Razorpay-Pod to the latest version 1.1.12. Let me know if that didn't solved the issue for you.

**Comment by navya15-ios** [comment]
> Hey @navya15-ios: Please update Razorpay-Pod to the latest version 1.1.12. Let me know if that didn't solved the issue for you.

Actually problem is with Mac pods were not installing
do you know how install pods in MacBook Air M1 chip? any other steps need to follow?
I used below command for installing cocoa pods :
sudo gem install cocoapods 

then I got below error: 

ERROR:  Loading command: install (LoadError)
	dlopen(/Library/Ruby/Gems/2.6.0/gems/date-3.1.1/lib/date_core.bundle, 0x0009): missing compatible arch in /Library/Ruby/Gems/2.6.0/gems/date-3.1.1/lib/date_core.bundle - /Library/Ruby/Gems/2.6.0/gems/date-3.1.1/lib/date_core.bundle
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass

**Comment by Nautiyalsachin** [comment]
@navya15-ios, This [link](https://stackoverflow.com/questions/23350388/cant-install-gems-because-undefined-method-invoke-with-build-args-for-nilni) will help you to resolve the above issue.

**Comment by raazii** [comment]
Swift Compiler Error (Xcode): Failed to build module 'Razorpay' from its module interface; the compiler that produced it, 'Apple Swift version 5.6
(swiftlang-5.6.0.323.62 clang-1316.0.20.8)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3.2
(swiftlang-1200.0.45 clang-1200.0.32.28)'


How to fix this?

**Comment by raazii** [comment]
> Swift Compiler Error (Xcode): Failed to build module 'Razorpay' from its module interface; the compiler that produced it, 'Apple Swift version 5.6 (swiftlang-5.6.0.323.62 clang-1316.0.20.8)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)'
> 
> How to fix this?

@Nautiyalsachin
