### ISSUE TITLE
Xcode9.3 Error missing required module RazorpayCommonCrypto

### ISSUE THREAD

**Issue by SwiftAmit** [razorpay/razorpay-pod#11]
![screen shot 2018-04-26 at 12 25 03 pm](https://user-images.githubusercontent.com/34594282/39290862-a9d08114-494e-11e8-9f95-7bbf14b422c3.png)

**Comment by iThink32** [comment]
hey can you clear your derived data and rebuild , also make sure that you are opening the workspace and not the project

**Comment by SwiftAmit** [comment]
already done a lot of time but same issues exist.

**Comment by imankitnpatel** [comment]
Hello,
I am getting the same error in version 1.0.14. Working fine with 1.0.13 but keep showing message new version is available.
Please help!

**Comment by iThink32** [comment]
Dont worry the message will only be displayed while using a test key or running on a simulator , if you run it on a device or using the live key the message will not be shown.

**Comment by iThink32** [comment]
Hey guys you are facing this error due to some internal inconsistency.However this is not reported by everyone. We are working on it but until then please downgrade the pod version to 1.0.12 for swif 4.1 or 1.0.11 for swift 3.1

**Comment by iThink32** [comment]
We have release a new version a few days back , please update and let us know if you still face this issue.
