### ISSUE TITLE
White Blank Page

### ISSUE THREAD

**Issue by karthikxcel** [razorpay/razorpay-pod#118]
## Description

When i open the razorpay ui using razorpay.open(options, displayController: self), only a blank white page appears. 

## Razorpay pod Version :

pod 'razorpay-pod' , '1.1.11'

## Xcode Version :
Version 12.2 

### What you did:

opening razorpay UI for making payment using razorpay.open(options, displayController: self)

### What happened:

Only a white blank page appeared & nothing is happening

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. razorpay.open(options, displayController: self)

## Code example, screenshot, or link to a repository:

        let options: [String:Any] = [
            "amount" : "1000", //mandatory in paise
            "description": "Pay to upgrade",
            "order_id": "9875",
            "image": "",
            "name": "XXXXX",
            "prefill": [
                "contact": "123456789",
                "email": ""
            ],
            "theme": [
                "color": "#3654DC"
            ]
        ]

        razorpay.open(options, displayController: self)

**Comment by Nautiyalsachin** [comment]
@karthikxcel, I would suggest you to check the implementation by referring our sample app. Let me know if you are still facing any issues.

**Comment by Nautiyalsachin** [comment]
Closing this issue for now, because of no response. Feel free to add more comments or re-opening the issue.
