### ISSUE TITLE
Razorpay not supporting for Swift Packge manager 

### ISSUE THREAD

**Issue by nagarajuios** [razorpay/razorpay-pod#132]
## Description

I tried to integrate on my swiftui project with swift package manager this SDK not supporting
 
## Xcode Version :
12.5

### What you did:

https://github.com/razorpay/razorpay-pod.git and added as 1.1.16 as my package version

### What happened:

there is no Package in manifest 

### Suggested solution:

Please do add package support for this SDK

**Comment by vivekjains** [comment]
Any update on this issue

**Comment by msatao** [comment]
+1

**Comment by iowais-dev** [comment]
+1

**Comment by jonathanjr3** [comment]
I have ported it to use spm, you can find it here: [Razorpay SPM](https://github.com/jonathanjr3/Razorpay-spm) use main branch for the update rule as I haven't made any release.

**Comment by pronav** [comment]
We've officially added support for Swift Package Manager sometime back: https://github.com/razorpay/razorpay-pod?tab=readme-ov-file#swift-package-manager-ios-13
