### ISSUE TITLE
not getting razorpay_signature this protocol not working RazorpayPaymentCompletionProtocolWithData 

### ISSUE THREAD

**Issue by virendrapatil0** [razorpay/razorpay-pod#143]
## Description

Please provide a clear and concise description of what the bug is. Include screenshots if needed.
Please test using the latest Razorpay pod release to make sure your issue has not already been fixed. 

## Razorpay pod Version :

Open `podfile` for checking the razorpay-pod version if it's not mentioned their then open `podfile.lock` and copy the pod version here. 

## Xcode Version :
Open Xcode > Go to `About Xcode` > copy the Xcode version here.

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.
2.

## Code example, screenshot, or link to a repository:
Please provide a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by virendrapatil0** [comment]
I am using  pod 'razorpay-pod', '~> 1.1.12'
Xcode 13.1, iOS deployment target - 12.0 

1. add the Protocol RazorpayPaymentCompletionProtocolWithData

extension PaymentDepositVC: RazorpayPaymentCompletionProtocolWithData {
    
    func onPaymentError(_ code: Int32, description str: String, andData response: [AnyHashable : Any]?) {
        print("error: ", code)
        self.presentAlert(withTitle: "Alert", message: str)
        
    }
    func onPaymentSuccess(_ payment_id: String, andData response: [AnyHashable : Any]?) {
        print("success: ", payment_id)
        self.presentAlert(withTitle: "Success", message: "Payment Succeeded")
        
    }
}

2 . Pass proper parameter payment form method and if payment success but not trigger in this Protocol method.

![Simulator Screen Shot - iPhone 11 Pro Max - 2022-01-28 at 10 49 56](https://user-images.githubusercontent.com/29115991/151506879-b1d21a80-5b9a-41de-a839-2a327a5315d5.png)

3. i am not getting the razorpay_signature

**Comment by virendrapatil0** [comment]
Hello Please let me know any changes

**Comment by ramprasadAnand** [comment]
Hi @virendrapatil0 can you please share the code to know how you are initialising the razorpay instance ?

**Comment by virendrapatil0** [comment]
import Razorpay

 var razorpay: RazorpayCheckout!

    override func viewDidLoad() {
        super.viewDidLoad()
        
        razorpay = RazorpayCheckout.initWithKey("rzp_test_pNufDOOeGRM3hI", andDelegate: self)
        
        //this method getting response order_id and pass payment form .
        generateOrderIdRazorpay()

    }
   
internal func showPaymentForm(order_id :String){
        
        
        let options: [String:Any] = [
                    "amount": amountRequested, //This is in currency subunits. 100 = 100 paise= INR 1.
                    "currency": "INR",//We support more that 92 international currencies.
                    "description": "",
                    "order_id": order_id,
                    "image": "",
                    "name": "business or product name",
                    "prefill": [
                        "contact": GlobalConstants.userData.mobileNumber!,
                        "email": GlobalConstants.userData.user_Email!
                    ],
                    "theme": [
                        "color": "#F37254"
                      ]
                ]
        //Both option try it
        //razorpay.open(options)
        razorpay.open(options, displayController: self)
    }

extension PaymentDepositVC: RazorpayPaymentCompletionProtocolWithData {
    
    func onPaymentError(_ code: Int32, description str: String, andData response: [AnyHashable : Any]?) {
        print("error: ", code)
        self.presentAlert(withTitle: "Alert", message: str)
        
    }
    func onPaymentSuccess(_ payment_id: String, andData response: [AnyHashable : Any]?) {
        print("success: ", payment_id)
       let paymentId = response?["razorpay_payment_id"] as! String
       let rezorSignature = response?["razorpay_signature"] as! String
        self.presentAlert(withTitle: "Success", message: "Payment Succeeded")
        
    }
}
//this Protocol work Properly
extension PaymentDepositVC : RazorpayPaymentCompletionProtocol {

    func onPaymentError(_ code: Int32, description str: String) {
        print("error: ", code, str)

        ErrorView.isHidden = false
        changealertimg(imagename: "payment_failed", alerttitle: "Payment Failed!",amount:amountRequested,amountstring:"Amount UnPaid", currenttime: getcurrentdatetime(), transactionID: self.orderID)
    }

    func onPaymentSuccess(_ payment_id: String) {
        print("success: ", payment_id)

        ErrorView.isHidden = true
        changealertimg(imagename: "payment_successful", alerttitle: "Payment Successful!",amount:amountRequested,amountstring:"Amount Paid", currenttime: getcurrentdatetime(), transactionID: self.orderID)
        checkTransactionStatusRazorpay(Orderid: self.orderID, razorpaypaymentid: payment_id,razorpayorderid: self.orderidDB ,razorpaysignature: "")
    }
}

**Comment by ramprasadAnand** [comment]
@virendrapatil0 if you want to get the callback to **RazorpayPaymentCompletionProtocolWithData** protocol methods you have to initialise our razorpay instance as given below.

`razorpay = RazorpayCheckout.initWithKey("rzp_test_pNufDOOeGRM3hI", andDelegateWithData: self)`

in your case you are delegating to **RazorpayPaymentCompletionProtocol** protocol, this is the reason you are not getting callback to **RazorpayPaymentCompletionProtocolWithData** methods.

**Comment by virendrapatil0** [comment]
Issue Solve Thanks

**Comment by ramprasadAnand** [comment]
Closing the issue as it got resolved.
