### ISSUE TITLE
header '/Applications/Developer/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.0.sdk/usr/include/CommonCrypto/CommonCrypto.h' not found

### ISSUE THREAD

**Issue by PulkitAppz** [razorpay/razorpay-pod#28]
I have just updated the pod version for Swift 4.1 and when I build my code , I am getting this error.

```
header '/Applications/Developer/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/CommonCrypto/CommonCrypto.h' not found
    header "/Applications/Developer/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/CommonCrypto/CommonCrypto.h"
           ^
<unknown>:0: error: could not build Objective-C module 'RazorpayCommonCrypto'
```

**Comment by iThink32** [comment]
can you please provide all the details that is specified while creating an issue?

**Comment by ashokadichill** [comment]
Hi

here is possible replicate of the issue by doing the following things

I have Xcode 9.2 
I need to update to swift 4.1 so i have download  Xcode 9.3.
my Xcode 9.3 will be kept inside my downloads 
my Xcode 9.2 will be kept in Application 

For clarity of XCode I have renamed the my Xcode 9.2 version to Xcode_9.2

So  my Razor Pay header ->
header '/Applications/Xcode.app/..../CommonCrypto.h

<unknown>:0: error: could not build Objective-C module 'RazorpayCommonCrypto'

Once i have renamed my Xcode_9.2 into Xcode all works fine.

**Comment by iThink32** [comment]
Yes two things , We do not support Xcode 9.2 anymore , please use Xcode 9.3+ and use the latest version.
Secondly the name of your default Xcode is important , we have added a script to cocoa pods to set our Xcode path based on your Xcode's name.This is the first such issue faced , please continue using your fix and ill give it a look in the next release.
