### ISSUE TITLE
Framework compiled with swift 4.1

### ISSUE THREAD

**Issue by Vidhyadharan-Mohanram** [razorpay/razorpay-pod#3]
Xcode 9.3 has been released, along with it swift 4.1 is available now, due to swift's lack of ABI Stability a new framework compiled with swift 4.1 is required to use Xcode 9.3...

**Comment by tuhinsbuddy** [comment]
Please compile with the latest Swift version(i.e. 4.1) which is necessary for Xcode 9.3

**Comment by Abishek10** [comment]
I am getting the following error after updating my Xcode. Please provide some workaround to this.

Module compiled with Swift 4.0.2 cannot be imported in Swift 4.1

**Comment by AbhinavArora95** [comment]
Hi, we are updating our frameworks and the one compiled with Swift 4.1 will be released by tomorrow

**Comment by Vidhyadharan-Mohanram** [comment]
for anyone using bitcode razorpay has provided the link "https://rzp-mobile.s3.amazonaws.com/ios/checkout/1.0.12/RazorpayBitcodeX9.framework.zip" to download the bitcode enabled version of their framework compiled with swift 4.1.
