### ISSUE TITLE
Issue With Xcode 10

### ISSUE THREAD

**Issue by kalrashubham49** [razorpay/razorpay-pod#32]
When running App in Xcode 10 facing below mentioned issue , Can you please check and let us know what it could be ?

dyld: Symbol not found: __T0BOWV
  Referenced from: /Users/shubham/Library/Developer/CoreSimulator/Devices/2B66CCB9-52E7-469E-964B-C72B33891F02/data/Containers/Bundle/Application/23809513-FD0A-49FA-B0D4-AFF9C0E78F8D/Guesthouser Staging.app/Frameworks/Razorpay.framework/Razorpay
  Expected in: /Users/shubham/Library/Developer/CoreSimulator/Devices/2B66CCB9-52E7-469E-964B-C72B33891F02/data/Containers/Bundle/Application/23809513-FD0A-49FA-B0D4-AFF9C0E78F8D/Guesthouser Staging.app/Frameworks/libswiftCore.dylib
 in /Users/shubham/Library/Developer/CoreSimulator/Devices/2B66CCB9-52E7-469E-964B-C72B33891F02/data/Containers/Bundle/Application/23809513-FD0A-49FA-B0D4-AFF9C0E78F8D/Guesthouser Staging.app/Frameworks/Razorpay.framework/Razorpay

**Comment by nikilesh122** [comment]
iam getting such a error **Module compiled with Swift 4.1 cannot be imported by the Swift 4.2 compiler:** at the import statement

**Comment by kalrashubham49** [comment]
Request you to expeditely look into the issue, as we have a very important build to go live.

**Comment by iThink32** [comment]
Hey @kalrashubham49 @ManoharaK , we are working on Xcode 10 support and will make a release on 28th September.

@ManoharaK Live apps will not be affected , you don't need to worry.
