### ISSUE TITLE
Issue With Xcode 10

### ISSUE THREAD

**Issue by lintocj** [razorpay/razorpay-pod#33]
- [x] I have gone through the README.(https://github.com/razorpay/razorpay-pod)
- [x] I have searched for a similar issue (https://github.com/razorpay/razorpay-pod/issues)
- [x] I am using the latest version of our framework (https://github.com/razorpay/razorpay-pod/releases)
- [x] I have cleaned my project, deleted derived data and rebuilt it.

dyld: Symbol not found: __T0BOWV Referenced from: /private/var/containers/Bundle/Application/6A97F623-38DD-4372-9DC8-E1EEADC104E0/Pinakin.app/Frameworks/Razorpay.framework/Razorpay Expected in: /private/var/containers/Bundle/Application/6A97F623-38DD-4372-9DC8-E1EEADC104E0/Pinakin.app/Frameworks/libswiftCore.dylib in /private/var/containers/Bundle/Application/6A97F623-38DD-4372-9DC8-E1EEADC104E0/Pinakin.app/Frameworks/Razorpay.framework/Razorpay. 

Giving an error after updating to xcode 10

## IDE Specs

XCODE 10 , Package Version :- razorpay-pod', '1.0.22'

**Comment by iThink32** [comment]
We are aware of this issue , it is because Xcode 10 supports Swift 4.2 and above and our framework is compiled with Swift 4.1.We are making a release on September 28th for this , please wait till then.
