### ISSUE TITLE
Having issue with xcode 10

### ISSUE THREAD

**Issue by ManoharaK** [razorpay/razorpay-pod#34]
Giving an error after updating to xcode 10. our app is in live, it will effect to iOS 12 users.

dyld: Symbol not found: __T0BOWV
Referenced from: /Users/manohar/Library/Developer/CoreSimulator/Devices/315C4D86-B68C-482C-8E7A-8FB882B77071/data/Containers/Bundle/Application/30A737EE-74B2-419D-980A-F32283D0DA1E/StayAbode.app/Frameworks/Razorpay.framework/Razorpay
Expected in: /Users/manohar/Library/Developer/CoreSimulator/Devices/315C4D86-B68C-482C-8E7A-8FB882B77071/data/Containers/Bundle/Application/30A737EE-74B2-419D-980A-F32283D0DA1E/StayAbode.app/Frameworks/libswiftCore.dylib
in /Users/manohar/Library/Developer/CoreSimulator/Devices/315C4D86-B68C-482C-8E7A-8FB882B77071/data/Containers/Bundle/Application/30A737EE-74B2-419D-980A-F32283D0DA1E/StayAbode.app/Frameworks/Razorpay.framework/Razorpay
(lldb)

**Comment by iThink32** [comment]
No it will not affect iOS 12 users.

We are aware of this issue , it is because Xcode 10 supports Swift 4.2 and above and our framework is compiled with Swift 4.1.We are making a release on September 28th for this , please wait till then.

**Comment by ManoharaK** [comment]
@iThink32 thanks fro quick replay
