### ISSUE TITLE
Swift 4.2 Compiler error

### ISSUE THREAD

**Issue by Nitinbond** [razorpay/razorpay-pod#37]
Module compiled with Swift 4.1 cannot be imported by the Swift 4.2 compiler: /Users/sandeepankumar/Desktop/design/LawzGrid_Customer_4.0_Renew/Pods/razorpay-pod/Pod/Razorpay.framework/Modules/Razorpay.swiftmodule/x86_64.swiftmodule
![screenshot 2018-09-28 at 3 51 34 pm](https://user-images.githubusercontent.com/11436995/46203134-7138d380-c336-11e8-9ca1-2547cb1f1b89.png)

**Comment by iThink32** [comment]
@Nitinbond please update to the latest version.
