### ISSUE TITLE
Attempt to present <UINavigationController> on <HomeTabBarController> whose view is not in the window hierarchy.

### ISSUE THREAD

**Issue by akashvercetti** [razorpay/razorpay-pod#38]
Xcode 10, iOS 12, Swift 4.2.

After upgrading to the latest Pod, I'm not able to present the Razorpay scene. 
The console message I get is 
`Warning: Attempt to present <UINavigationController: 0x10527fe00> on <**HomeTabBarController**: 0x104559df0> whose view is not in the window hierarchy!`

The reason I'm guessing for this is, the Razorpay scene is presented on the key window's **RootViewController** , and in many cases like ours, the **RootViewController**(in this case, **TabBarControler**) might be so far behind in the hierarchy because of presented controllers on top of it that it would be impossible to present the Razorpay scene.

Could you please look into this edge case?

**Comment by iThink32** [comment]
hey @akashvercetti Razorpay first checks if you have a navigation controller , if you do pushed on top of everything else presents on the topviewcontroller.

**Comment by iThink32** [comment]
@akashvercetti  this is the standard procedure that is usually followed on iOS so changing it would be difficult , please let me know if there is any other way I can help you.

**Comment by akashvercetti** [comment]
Just throwing this idea out there, but could you create an additional `.open` method which accepts a `presenting controller` parameter and maybe a `push/present enum` value? This method would allow us present/push razorpay scenes from a viewController of our choice. You can keep the original `.open` method intact as it is.

**Comment by rkpradeep20** [comment]
Hey, I'm facing the same issue. I'm trying to present Razorpay over a navigation controller. But, it's throwing an error. 
From what I have analyzed, razorpay is trying to present the screen from the RootVC. I guess that's the reason for this issue. 
There are two scenarios where I see issues arising: One in a container or another when there is no container.
Can you change the view controller in the framework with conditions to check if it has a parentViewController(Incase of ContainerVC) if not make it present on the delegate associated VC.
That would be a quick fix.

**Comment by rkpradeep20** [comment]
I found one more thing helpful. I you are setting the view controller by this method:
if var topController = UIApplication.sharedApplication().keyWindow?.rootViewController, Then here is helpful link: 
https://stackoverflow.com/questions/26667009/get-top-most-uiviewcontroller
Getting the topmost view controller
if var topController = UIApplication.sharedApplication().keyWindow?.rootViewController {
    while let presentedViewController = topController.presentedViewController {
        topController = presentedViewController
    }

    // topController should now be your topmost view controller
}

Then Presenting the razorpay view using topController would work. 

I would appreciate a quick fix as the development on the iOS end has stalled because of this issue. We have a deadline and on a time crunch to deliver the app by dussehra.

Thanks,
Pradeep.

**Comment by iThink32** [comment]
@akashvercetti ok good suggestion but can u give me a few use cases where the current implementation is difficult to handle

**Comment by iThink32** [comment]
@rkpradeep20 our ViewController is only presented in case your rootviewcontroller is not a UINavigationController , else it is pushed on to the navigation stack.
In response to your link , I can present it on the top most controller but don't you thing it is not a good idea?
Ideally a given controller A should present only one screen at a time , presenting multiple controllers is usually not a good approach , if you want to display screen A after screen B and so forth a navigation controller is preferred. 

Let me know if can help you in any other way.

**Comment by rkpradeep20** [comment]
@iThink32 I totally agree with your argument. Let me just give your my current scenario, and what issue I'm facing.
My View Hierarchy:

Root View Controller: Initial View Controller
UINavigationViewController: Checkout Flow Navigation Stack

Checkout Flow Navigation Stack is presented on top of Initial View Controller to complete buying the product. 
If as you mentioned, razorpay should be able to push itself onto Checkout Flow Navigation stack, but it is not. Its trying to present a new navigation controller on top of Initial View Controller which is the Root View Controller, and not get pushed onto the Checkout Flow Navigation Stack.

Warning: Attempt to present <UINavigationController: 0x7fb50b806c00> on <Jyothirvaibhava.Initial_ViewController: 0x7fb5076083a0> whose view is not in the window hierarchy!

I did not have any issue with this when I was testing the app on iOS 11 just 10 3 days back. We were waiting for razorpay framework to be compiled with swift 4.2 and start making the required fixes for iOS 12 before releasing the app. So, can you please check back on your end and let us know.

Thanks,
Pradeep.

**Comment by nikilesh122** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/28642835/46253487-84fd4a80-c49a-11e8-8954-7da503a3309e.gif)

hi iam launchin razor-pay page in navigation controller when launched the razor pay page it comes back to my page but the navigation bar is lost

**Comment by iThink32** [comment]
@rkpradeep20 your pictures clearly shows that Razorpay is being pushed on to your nav stack (check the animation or try printing navVC.viewcontrollers), the issue Warning: Attempt to present <UINavigationController: 0x7fb50b806c00> on <Jyothirvaibhava.Initial_ViewController: 0x7fb5076083a0> whose view is not in the window hierarchy! is not because to that 

check this link

https://stackoverflow.com/questions/11862883/attempt-to-present-uiviewcontroller-on-uiviewcontroller-whose-view-is-not-in-the

it is because your are calling open before a navigation completes.

**Comment by iThink32** [comment]
@akashvercetti I think you should also have a look at the link shared above.

**Comment by rkpradeep20** [comment]
I'm pretty sure @akashvercetti  and I made our point and clearly addressed the issue. The link you provided helpful for people who try to present the View Controller in viewDidLoad method. But the issue we are facing and the solution you are giving us is no way relevant.

Thanks for no help.

**Comment by iThink32** [comment]
@rkpradeep20 it is occurring because we are checking the type of your rootviewcontroller , in your case it is not a UINavigationController due to which it is getting presented , to get things clear just take a sample app and test it with/without a navigation controller and it will clearly explain what is happening.

**Comment by rkpradeep20** [comment]
The sample app is not working its crashing on launch.

The log:

<img width="1440" alt="screen shot 2018-09-30 at 4 13 26 pm" src="https://user-images.githubusercontent.com/15925427/46256689-c78b4b00-c4cb-11e8-99e3-222e7b376546.png">

**Comment by rkpradeep20** [comment]
We should be able to launch the payment screen on any View Controller, not just from root view controller.

**Comment by iThink32** [comment]
@rkpradeep20 by sample app I mean create your own sample app and test , yes we can launch the payment screen on any controller , give it a try.

**Comment by rkpradeep20** [comment]
I have made a test project as you requested and I'm still facing the issue. 
Please clone the project from the link below to have a look:
https://github.com/rkpradeep20/RazorpayTest

Gif of the screen grab for the above project.
![image](https://user-images.githubusercontent.com/15925427/46257303-f823b280-c4d4-11e8-969a-8826f6cd648f.gif)

**Comment by iThink32** [comment]
@rkpradeep20 yes that was my point from the beginning if your rootviewcontroller is a uinavigationcontroller it will push else it will present on the rootViewController

**Comment by akashvercetti** [comment]
Please forward the working sample app to me at carljohnson.akash@gmail.com

Or post it somewhere on github

**Comment by akashvercetti** [comment]
@iThink32 I think the best solution would be to make a new .**open** function where you would let us choose the presenting controller and let us decide if we want to **push** or **present**. This is probably the best and most flexible solution for everyone.

**Comment by iThink32** [comment]
@akashvercetti suggestion taken will take this up for the next release.Anyway regarding the sample app , as of now we have not uploaded any Swift sample app so ill modify the one @rkpradeep20 has sent and send it to both of you in a while.

**Comment by iThink32** [comment]
@akashvercetti the next release will have the following fix :-

open() method will have a presentationViewController option , if you specify this we will use this to present our checkout screen. We are going to continue using the rootController to perform push.

**Comment by Abishek10** [comment]
@iThink32 Please mail the working sample app to abishek@mykarmaapp.com

**Comment by iThink32** [comment]
@akashvercetti its not a good approach to present a viewController over a navigationController , anyway the next release will have the open(displayController) method with which you can specify the viewController on which our Controller has to be displayed.

**Comment by iThink32** [comment]
@rkpradeep20  the next release will have the open(displayController:) method with which you can specify the viewController on which our Controller has to be displayed.

**Comment by akashvercetti** [comment]
> @akashvercetti its not a good approach to present a viewController over a navigationController ,you must push it on the stack.Anyway the next release will have the open(displayController:) method with which you can specify the viewController on which our Controller has to be displayed.

I guess I didn't explain it properly, We present it over a view Controller at the top of the navigation controller stack, not the navigation controller itself. But I guess I will have to wait for the next release.

**Comment by iThink32** [comment]
@akashvercetti ok , keep a watch at the readme we will be making a release within a day or two

**Comment by iThink32** [comment]
@akashvercetti a new version has been released , please update.

**Comment by iThink32** [comment]
closing as this issue has been fixed , please reopen if you continue facing any issue

**Comment by ShahnaHassan** [comment]
can anyone help me with the simplest solution for this issue?

**Comment by iThink32** [comment]
@ShahnaHassan this issue has been fixed long back , please refer the readme for more details.

**Comment by ShahnaHassan** [comment]
Sir,
I would like to know how can we get the payment details like paid amount
payment mode etc..by passing the paymentId.
Kindly reply me as soon as possible.

**Comment by iThink32** [comment]
@ShahnaHassan both of the above have to done via the admin dashboard , there is no provision for it via the SDK.

**Comment by ShahnaHassan** [comment]
Thank You Sir

**Comment by ShahnaHassan** [comment]
I would also like to know whether will you provide these functionalities in
future via SDK?

**Comment by iThink32** [comment]
@ShahnaHassan its currently not in our roadmap as of now , will update the readme if we expose such a feature in future.

**Comment by ShahnaHassan** [comment]
Thank you!

**Comment by Rushi271193** [comment]
Attempt to present <UINavigationController: 0x7f8c6390ae00>  on <UIViewController: 0x7f8c6341fe90> which is already presenting <RCTModalHostViewController: 0x7f8c6349b7a0>
/Users/travis/build/razorpay/razorpay-ios/RazorpayIOS/CheckoutOtpelf/Classes/RazorpayCheckoutVC.swift deinitialized

getting this issue for react native razorpay.  As you have mentioned there ways to solve it in native ios but how do we overcome it in react native as we dont use the viewcontrollers to push any view

**Comment by DhrubojyotiBis1** [comment]
I am facing this problem now.

**Comment by kingglov** [comment]
For me its worked and my scenario is ,
![Screenshot 2019-12-20 at 11 09 00](https://user-images.githubusercontent.com/50819408/71233554-f7667e80-231b-11ea-8cf1-a13782da2ce9.png)

first i have a login view Controller ,  after login or skipping that it takes to a tabbar controller . after that i've selected a product and try to present the rozarpay but its showing the error that not in window hierarchy . 
<img width="1408" alt="Screenshot 2019-12-20 at 11 11 19" src="https://user-images.githubusercontent.com/50819408/71233559-fdf4f600-231b-11ea-9a62-25f076cabda5.png">

Here i found the reason that my root controller is login view controller but i am presenting in tabbar controller . and i've implemented if user pressed skip or logged it should check in the app deligate and set the root controller inside the appDeligate.
so now if you close and reopen the app(not run from xcode just close and reopen) in device or simulator the app deligate sets the rootViewController to tabbarcontroller. so , now if you try to call it should work. there is no error and rozarpay was opening.
<img width="468" alt="Screenshot 2019-12-20 at 11 12 23" src="https://user-images.githubusercontent.com/50819408/71233567-03524080-231c-11ea-9ade-abb832118358.png">

And the final solution is set the rootview controller inside login view controller i.e. user pressed skip or logged in. then it should work.

**Comment by DeveloperAsim0** [comment]
Still in 2020 getting the same issue with latest version. And cannot find any solution yet.
please help me... I searched the documentation but I couldn't find it 

Thanks in advanced
