### ISSUE TITLE
<unknown>:0: error: module compiled with Swift 4.1 cannot be imported by the Swift 4.2 compiler

### ISSUE THREAD

**Issue by ChandraPrakashJangid** [razorpay/razorpay-pod#40]
- [x] I have gone through the README.(https://github.com/razorpay/razorpay-pod)
- [x] I have searched for a similar issue (https://github.com/razorpay/razorpay-pod/issues)
- [x] I am using the latest version of our framework (https://github.com/razorpay/razorpay-pod/releases)
- [x] I have cleaned my project , deleted derived data and rebuilt it.

Before update of Xcode my app was working perfectly. But as soon as I updated app showing me error. 
Here is the error:
<unknown>:0: error: module compiled with Swift 4.1 cannot be imported by the Swift 4.2 compiler: /Users/chandra/Developer/speedmeter/SpeedMeter/Razorpay.framework/Modules/Razorpay.swiftmodule/x86_64.swiftmodule

## IDE Specs

Xcode: 10.0
iOS: 12.0

**Comment by iThink32** [comment]
@ChandraPrakashJangid update to the latest version of our framework.Check the readme for more details.
