### ISSUE TITLE
Cannot find protocol declaration for 'ExternalWalletSelectionProtocol'

### ISSUE THREAD

**Issue by lintocj** [razorpay/razorpay-pod#43]
- [x] I have gone through the README.(https://github.com/razorpay/razorpay-pod)
- [x] I have searched for a similar issue (https://github.com/razorpay/razorpay-pod/issues)
- [x] I am using the latest version of our framework (https://github.com/razorpay/razorpay-pod/releases)
- [x] I have cleaned my project , deleted derived data and rebuilt it.

Cannot find protocol declaration for 'ExternalWalletSelectionProtocol'
Cannot find protocol declaration for 'RazorpayPaymentCompletionProtocol'

## IDE Specs

Xcode 10.(Objective c)
Pod 1.0.23
## Screenshots 

![screenshot 2018-10-03 at 11 37 48 am](https://user-images.githubusercontent.com/20218814/46393703-f2f87a80-c703-11e8-9ca8-628973ac3749.png)

**Comment by iThink32** [comment]
@lintocj delete your derived data and build again as it is working for other clients.

**Comment by lintocj** [comment]
@iThink32 Everything tried from my end, but getting the same error.

**Comment by lintocj** [comment]
I am trying from objective C, is there anything need to update from my end compared to the previous build(Pod 1.0.22). Currently, I am trying (Pod 1.0.24).

**Comment by iThink32** [comment]
@lintocj you have to include <Razorpay/Razorpay-Swift.h> instead of <Razorpay/Razorpay.h>

**Comment by lintocj** [comment]
@iThink32 Now it's showing like "No visible @interface for 'Razorpay' declares the selector 'open:'

**Comment by lintocj** [comment]
Okay. Working!. Please update your document.

**Comment by iThink32** [comment]
@lintocj updated. Closing as this issue is fixed.

**Comment by rmamtaventures** [comment]
i'm also facing same issue in xcode 12.

**Comment by chinthu** [comment]
> 

DId you resolved this issue ?

**Comment by ayushHello** [comment]
Hello 
As I am also facing same issue as mentioned above in Xcode version 14.0.1 and strange thing  is ---- The exact code is working on another system with same configuration and same Xcode version.
