### ISSUE TITLE
Checkout page not shown - Only white screen appears

### ISSUE THREAD

**Issue by parthbizmo** [razorpay/razorpay-pod#47]
- [x] I have gone through the README.(https://github.com/razorpay/razorpay-pod)
- [x] I have searched for a similar issue (https://github.com/razorpay/razorpay-pod/issues)
- [x] I am using the latest version of our framework (https://github.com/razorpay/razorpay-pod/releases)
- [x] I have cleaned my project , deleted derived data and rebuilt it.

When I try to open the checkout form using the razorpay.open() method, I am presented with a screen in which an activity indicator appears for 2-3 seconds then vanishes. The white screen stays for a long time in the same state. 

After a while, in the logs a message appears : "Could not signal service com.apple.WebKit.Networking: 113: Could not find specified service".

*I checked whether internet is working. All other API are working fine.

Also, this error can be seen sometimes in the logs : "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated"

The white screen stays like that. I waited for 15 minutes still nothing happens.

## IDE Specs
Xcode 10.0
Razorpay-pod '1.0.24'
macOS Mojave 10.14

## Retro Steps
Try to open razorpay.open(options) or razorpay.open(options, displayController: vc) methods after setting the options

**Comment by Karthikeyan-Thiru** [comment]
Same issue occurs in the version 1.0.18. Already APP is in live now

**Comment by iThink32** [comment]
@Karthikeyan-Thiru please update to our latest version and try.
@parthbizmo im not able to reproduce the issue on my end , can you create a test app yourself and try?

**Comment by parthbizmo** [comment]
@iThink32 : I think I found the solution. I am closing this issue. After the issue with razorpay-pod started occurring, after some time, xcode started showing me strange errors. Turns out, the issue is with macOS. It was not letting xcode create / update derived data files. Following is he issue and what I did to resolve it. Maybe it will be helpful for you in the future.

[Stackoverflow link for the issue: Too many files Opened](https://superuser.com/questions/433746/is-there-a-fix-for-the-too-many-open-files-in-system-error-on-os-x-10-7-1)

**Comment by iThink32** [comment]
@parthbizmo damn this was the fix? great anyway thanks.

**Comment by parthbizmo** [comment]
@iThink32 : Yep. I was able to replicate it again later yesterday. :grimacing:

**Comment by iThink32** [comment]
@parthbizmo let me know if you need any help from my end.

**Comment by DipamAmin** [comment]
We are encountering an issue when opening Razorpay’s checkout screen in an iOS WebView within a PWA. The specific issues are as follows:

NetBanking: When users select NetBanking as a payment option, a blank white screen appears, and the payment process cannot continue.

UPI: When users select UPI as a payment method, the WebView restarts unexpectedly, causing the user to lose their current session and requiring them to restart the transaction process.

Is there any solution for the above issue?
