### ISSUE TITLE
Issue in archiving with xcode 10.

### ISSUE THREAD

**Issue by Nautiyalsachin** [razorpay/razorpay-pod#50]
- [ ✔️] I have gone through the README.(https://github.com/razorpay/razorpay-pod)
- [ ✔️] I have searched for a similar issue (https://github.com/razorpay/razorpay-pod/issues)
- [ ✔️] I am using the latest version of our framework (https://github.com/razorpay/razorpay-pod/releases)
- [ ✔️] I have cleaned my project , deleted derived data and rebuilt it.

I am facing this issue 
Failed to verify bitcode in Razorpay.framework/Razorpay:
error: Cannot extract bundle from /var/folders/r3/cdrxd4vj0qb3hj2sxdlysxsc0000gn/T/XcodeDistPipeline.LtV/Root/Payload/Wizely.app/Frameworks/Razorpay.framework/Razorpay (x86_64)

When trying to create a build from Archive in Xcode 10.

## IDE Specs

Xcode 10.0

## Retro Steps

I have added the new framework from (https://razorpay.com/docs/ios-customui-sdk/#usage-instructions) and tried to build the same project with Xcode 10. 

## Screenshots

<img width="446" alt="screen shot 2018-10-29 at 9 16 13 pm" src="https://user-images.githubusercontent.com/14342956/47662350-bdd72f00-dbc0-11e8-9c0c-feae50bc99ac.png">

**Comment by iThink32** [comment]
@Nautiyalsachin we do not code sign our frameworks from our end.We ship our framework with simulator architectures , you must remove them before you create an archive.
have a look at the video on this page named creating an app archive:
https://razorpay.com/docs/ios/integration-videos/

**Comment by Nautiyalsachin** [comment]
@iThink32 Thank you for the quick reply and it worked too, it was working before in xcode 9 but now they are more strict about the release policy.

**Comment by Dineshfluper** [comment]
I have the same issue but still it is not solved, Iam using ios 11.0 swift 4.2

**Comment by Dineshfluper** [comment]
I have seen the integration video ,still not able to resolve it

**Comment by pronav** [comment]
- Use version pod 1.0.28 with swift 4.2
- See this comment to solve the archiving issue: https://github.com/razorpay/react-native-razorpay/issues/194#issuecomment-497368029

**Comment by Manoj741** [comment]
<img width="1168" alt="Screenshot 2020-01-16 at 8 22 15 AM" src="https://user-images.githubusercontent.com/28729128/72489541-601d1a00-383a-11ea-8b87-3692c5439a00.png">
I am using Xcode 10.3 and facing issue while exporting the archive with adhoc mode. please help me.

**Comment by jitrani** [comment]
@Manoj741 did you got any solution i also got same error.

**Comment by Nautiyalsachin** [comment]
@jitrani: Which Swift version are you using in your project? Please use the specific version of the frameworks from this [doc.](https://razorpay.com/docs/payment-gateway/ios-integration/standard)

**Comment by jitrani** [comment]
@Manoj741 Apple Swift version 5.0.1 (swiftlang-1001.0.82.4 clang-1001.0.46.5)  i am using this one.
