### ISSUE TITLE
Xcode 10.2 - Build Failed : Module compiled with Swift 4.2.1 cannot be imported by the Swift 5.0 compiler: /Pods/razorpay-pod/Pod/Razorpay.framework/Modules/Razorpay.swiftmodule/arm.swiftmodule

### ISSUE THREAD

**Issue by reallyram** [razorpay/razorpay-pod#56]
- [x ] I have gone through the README.(https://github.com/razorpay/razorpay-pod)
- [x ] I have searched for a similar issue (https://github.com/razorpay/razorpay-pod/issues)
- [x ] I am using the latest version of our framework (https://github.com/razorpay/razorpay-pod/releases)
- [x ] I have cleaned my project , deleted derived data and rebuilt it.

Xcode Build Failed

Module compiled with Swift 4.2.1 cannot be imported by the Swift 5.0 compiler: /Pods/razorpay-pod/Pod/Razorpay.framework/Modules/Razorpay.swiftmodule/arm.swiftmodule
## IDE Specs

Xcode 10.2
Razorpay pod 1.0.28

**Comment by shahnawazali** [comment]
I am also facing this issue

/Razorpay.framework/Razorpay compiled with older version of Swift language (unknown ABI version 0x06) than previous files (unknown ABI version 0x07) file /Razorpay.framework/Razorpay' for architecture armv7

**Comment by parthbizmo** [comment]
I am also facing the same issue. Please update the module to be Swift 5 compatible

**Comment by AbhinavArora95** [comment]
Hi. Apologies for the delay in releasing. We are working on the new release and should be released in a couple of days.

**Comment by Krtic** [comment]
I am also facing the same problem. Waiting for swift 5 compatible one.

**Comment by rkpradeep20** [comment]
Facing the same issue here. Would like a build built with the latest xcode 10.2.

**Comment by Krtic** [comment]
Any update ??????

**Comment by reallyram** [comment]
@AbhinavArora95 Can we have an estimated release date? As you might know it is a blocker for us to debug the App on iOS 12.2 devices. To debug on iOS 12.2 we need to use Xcode10.2

**Comment by rkpradeep20** [comment]
@AbhinavArora95 Would appreciate information on the release date. Same as above ☝️.

**Comment by Krtic** [comment]
gonna change to pay u money... this one is a blocker...  razor pay was a nice one...

**Comment by SuganyaEkambaram** [comment]
same issue, Early Release would be appreciated!

**Comment by Krtic** [comment]
You can download the framework compiled in swift 5 here https://razorpay.com/docs/ios/

**Comment by AbhinavArora95** [comment]
Hi. Apologies for not updating over here. It's often tough to update everywhere. Nevertheless, as mentioned by @Krtic , you can find the updated framework [here]( https://razorpay.com/docs/ios/) . It was released on 1st April and NO it wasn't an April Fools prank.

**Comment by Saikumar-Reddy** [comment]
Guys could you find any solution for this issue

**Comment by vinny3273** [comment]
still not resolved. xcode gives me this error.
../ios/Pods/razorpay-pod/Pod/Razorpay.framework/Razorpay compiled with older version of Swift language (4.1/4.2) than previous files (5 or later)

**Comment by Nautiyalsachin** [comment]
Please follow this table for finding respected versions - https://razorpay.com/docs/payment-gateway/ios-integration/standard/

**Comment by Saikumar-Reddy** [comment]
I already tried all the standard versions from the given table, but still getting the same error 😟. I tried both pods install and adding the framework manually to the project.

**Comment by vinny3273** [comment]
@Nautiyalsachin i did install for Objective-C and removed razorpay from Podfile. its working now. thanks
xcode - 11.2.1
react native - 0.60.4
react-native-razorpay - 2.1.30
