### ISSUE TITLE
image not found issue with XCode Version 10.2 (10E125) with swift 5 and Objective-C integration

### ISSUE THREAD

**Issue by sureshcapternal** [razorpay/razorpay-pod#58]
- [x] I have gone through the README.(https://github.com/razorpay/razorpay-pod)
- [x] I have searched for a similar issue (https://github.com/razorpay/razorpay-pod/issues)
- [x] I am using the latest version of our framework (https://github.com/razorpay/razorpay-pod/releases)
- [x] I have cleaned my project , deleted derived data and rebuilt it.

I have XCode Version 10.2 (10E125)
with swift 5
I'm trying to integrate razorpay with Objective-C. I have installed razorpay using :

pod 'razorpay-pod', '1.0.28'

project build successfully but getting runtime error as :

dyld: Library not loaded: @rpath/libswiftCore.dylib
Referenced from: /Users/capternal/Library/Developer/CoreSimulator/Devices/C14B2FF6-49C0-4398-8D0F-C5893EE20BC3/data/Containers/Bundle/Application/2E01BDB6-55E3-4CA5-B540-B1CB7348559B/customer_stage.app/Frameworks/Razorpay.framework/Razorpay
Reason: image not found

can anyone help me with this?

**Comment by laralb** [comment]
I am also getting the same issue

**Comment by AbhinavArora95** [comment]
Hi, the razorpay-pod was updated a few days back to 1.1.1 with Swift 5 compiled framework. Please update the pod.

**Comment by laralb** [comment]
hi , i updated my pod now  razorpay version is 1.1.2  and Xcode version is
10.2.1 (10E1001) but still i get same issue "*RazorpayCheckoutVC.swift
deinitialized*". please give me proper solution for
this issue. every xcode update i got issue. i can't complete my project.

Xcode show this issue.

*2019-04-23 13:15:34.677110+0530 RazorpayNewSDK[2878:144187] [Client]
Remote object proxy returned error: Error Domain=NSCocoaErrorDomain
Code=4099 "The connection to service named
com.apple.commcenter.coretelephony.xpc was invalidated."
UserInfo={NSDebugDescription=The connection to service named
com.apple.commcenter.coretelephony.xpc was invalidated.}*

*2019-04-23 13:15:34.677398+0530 RazorpayNewSDK[2878:144187] [Client]
Remote object proxy returned error: Error Domain=NSCocoaErrorDomain
Code=4099 "The connection to service named
com.apple.commcenter.coretelephony.xpc was invalidated."
UserInfo={NSDebugDescription=The connection to service named
com.apple.commcenter.coretelephony.xpc was invalidated.}*

*2019-04-23 13:15:34.677537+0530 RazorpayNewSDK[2878:144190] [Client]
Sending selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099
"The connection to service named com.apple.commcenter.coretelephony.xpc was
invalidated." UserInfo={NSDebugDescription=The connection to service named
com.apple.commcenter.coretelephony.xpc was invalidated.}*

*2019-04-23 13:15:34.677612+0530 RazorpayNewSDK[2878:144049] [Client]
Synchronous remote object proxy returned error: Error
Domain=NSCocoaErrorDomain Code=4099 "The connection to service named
com.apple.commcenter.coretelephony.xpc was invalidated."
UserInfo={NSDebugDescription=The connection to service named
com.apple.commcenter.coretelephony.xpc was invalidated.}*

*2019-04-23 13:15:34.677801+0530 RazorpayNewSDK[2878:144190] [Client]
Sending selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099
"The connection to service named com.apple.commcenter.coretelephony.xpc was
invalidated." UserInfo={NSDebugDescription=The connection to service named
com.apple.commcenter.coretelephony.xpc was invalidated.}*

*2019-04-23 13:15:34.677819+0530 RazorpayNewSDK[2878:144049] [NetworkInfo]
Descriptors query returned error: Error Domain=NSCocoaErrorDomain Code=4099
"The connection to service named com.apple.commcenter.coretelephony.xpc was
invalidated." UserInfo={NSDebugDescription=The connection to service named
com.apple.commcenter.coretelephony.xpc was invalidated.}*

*2019-04-23 13:15:34.678601+0530 RazorpayNewSDK[2878:144049] [Client]
Synchronous remote object proxy returned error: Error
Domain=NSCocoaErrorDomain Code=4099 "The connection to service named
com.apple.commcenter.coretelephony.xpc was invalidated."
UserInfo={NSDebugDe2019-04-23 13:15:34.678674+0530
RazorpayNewSDK[2878:144190] [Client] Remote object proxy returned error:
Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named
com.apple.commcenter.coretelephony.xpc was invalidated."
UserInfo={NSDebugDescription=The connection to service named
com.apple.commcenter.coretelephony.xpc was invalidated.}*

*scription=The connection to service named
com.apple.commcenter.coretelephony.xpc was invalidated.}*

*2019-04-23 13:15:34.683175+0530 RazorpayNewSDK[2878:144049] [NetworkInfo]
Descriptors query returned error: Error Domain=NSCocoaErrorDomain Code=4099
"The connection to service named com.apple.commcenter.coretelephony.xpc was
invalidated." UserInfo={NSDebugDescription=The connection to service named
com.apple.commcenter.coretelephony.xpc was invalidated.}*

*2019-04-23 13:15:34.683190+0530 RazorpayNewSDK[2878:144187] [Client]
Sending selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099
"The connection to service named com.apple.commcenter.coretelephony.xpc was
invalidated." UserInfo={NSDebugDescription=The connection to service named
com.apple.commcenter.coretelephony.xpc was invalidated.}*

*2019-04-23 13:15:34.683862+0530 RazorpayNewSDK[2878:144049] [Client]
Synchronous remote object proxy returned error: Error
Domain=NSCocoaErrorDomain Code=4099 "The connection to service named
com.apple.commcenter.coretelephony.xpc was invalidated."
UserInfo={NSDebugDescription=The connection to service named
com.apple.commcenter.coretelephony.xpc was invalidated.}*

*2019-04-23 13:15:34.683942+0530 RazorpayNewSDK[2878:144187] [Client]
Remote object proxy returned error: Error Domain=NSCocoaErrorDomain
Code=4099 "The connection to service named
com.apple.commcenter.coretelephony.xpc was invalidated."
UserInfo={NSDebugDescription=The connection to service named
com.apple.commcenter.coretelephony.xpc was invalidated.}*

*2019-04-23 13:15:34.684016+0530 RazorpayNewSDK[2878:144049] [NetworkInfo]
Descriptors query returned error: Error Domain=NSCocoaErrorDomain Code=4099
"The connection to service named com.apple.commcenter.coretelephony.xpc was
invalidated." UserInfo={NSDebugDescription=The connection to service named
com.apple.commcenter.coretelephony.xpc was invalidated.}*

*2019-04-23 13:15:34.684189+0530 RazorpayNewSDK[2878:144187] [Client]
Sending selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099
"The connection to service named com.apple.commcenter.coretelephony.xpc was
invalidated." UserInfo={NSDebugDescription=The connection to service named
com.apple.commcenter.coretelephony.xpc was invalidated.}*

*2019-04-23 13:15:34.711229+0530 RazorpayNewSDK[2878:144049] [Client]
Synchronous remote object proxy returned error: Error
Domain=NSCocoaErrorDomain Code=4099 "The connection to service named
com.apple.commcenter.coretelephony.xpc was invalidated."
UserInfo={NSDebugDescription=The connection to service named
com.apple.commcenter.coretelephony.xpc was invalidated.}*

*2019-04-23 13:15:34.711310+0530 RazorpayNewSDK[2878:144187] [Client]
Remote object proxy returned error: Error Domain=NSCocoaErrorDomain
Code=4099 "The connection to service named
com.apple.commcenter.coretelephony.xpc was invalidated."
UserInfo={NSDebugDescription=The connection to service named
com.apple.commcenter.coretelephony.xpc was invalidated.}*

*2019-04-23 13:15:34.711419+0530 RazorpayNewSDK[2878:144049] [NetworkInfo]
Descriptors query returned error: Error Domain=NSCocoaErrorDomain Code=4099
"The connection to service named com.apple.commcenter.coretelephony.xpc was
invalidated." UserInfo={NSDebugDescription=The connection to service named
com.apple.commcenter.coretelephony.xpc was invalidated.}*

*2019-04-23 13:15:34.711495+0530 RazorpayNewSDK[2878:144187] [Client]
Remote object proxy returned error: Error Domain=NSCocoaErrorDomain
Code=4099 "The connection to service named
com.apple.commcenter.coretelephony.xpc was invalidated."
UserInfo={NSDebugDescription=The connection to service named
com.apple.commcenter.coretelephony.xpc was invalidated.}*

*2019-04-23 13:15:34.711588+0530 RazorpayNewSDK[2878:144190] [Client]
Sending selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099
"The connection to service named com.apple.commcenter.coretelephony.xpc was
invalidated." UserInfo={NSDebugDescription=The connection to service named
com.apple.commcenter.coretelephony.xpc was invalidated.}*

*2019-04-23 13:15:34.712148+0530 RazorpayNewSDK[2878:144190] [Client]
Sending selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099
"The connection to service named com.apple.commcenter.coretelephony.xpc was
invalidated." UserInfo={NSDebugDescription=The connection to service named
com.apple.commcenter.coretelephony.xpc was invalidated.}*

*2019-04-23 13:15:34.712922+0530 RazorpayNewSDK[2878:144190] [Client]
Remote object proxy returned error: Error Domain=NSCocoaErrorDomain
Code=4099 "The connection to service named
com.apple.commcenter.coretelephony.xpc was invalidated."
UserInfo={NSDebugDescription=The connection to service named
com.apple.commcenter.coretelephony.xpc was invalidated.}*

*2019-04-23 13:15:34.713302+0530 RazorpayNewSDK[2878:144187] [Client]
Sending selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099
"The connection to service named com.apple.commcenter.coretelephony.xpc was
invalidated." UserInfo={NSDebugDescription=The connection to service named
com.apple.commcenter.coretelephony.xpc was invalidated.}*

*2019-04-23 13:15:34.713322+0530 RazorpayNewSDK[2878:144049] [Client]
Synchronous remote object proxy returned error: Error
Domain=NSCocoaErrorDomain Code=4099 "The connection to service named
com.apple.commcenter.coretelephony.xpc was invalidated."
UserInfo={NSDebugDescription=The connection to service named
com.apple.commcenter.coretelephony.xpc was invalidated.}*

*2019-04-23 13:15:34.713757+0530 RazorpayNewSDK[2878:144049] [NetworkInfo]
Descriptors query returned error: Error Domain=NSCocoaErrorDomain Code=4099
"The connection to service named com.apple.commcenter.coretelephony.xpc was
invalidated." UserInfo={NSDebugDescription=The connection to service named
com.apple.commcenter.coretelephony.xpc was invalidated.}*

*2019-04-23 13:15:34.715044+0530 RazorpayNewSDK[2878:144049] [Client]
Synchronous remote object proxy returned error: Error
Domain=NSCocoaErrorDomain Code=4099 "The connection to service named
com.apple.commcenter.coretelephony.xpc was invalidated."
UserInfo={NSDebugDescription=The connection to service named
com.apple.commcenter.coretelephony.xpc was invalidated.}*

*2019-04-23 13:15:34.715122+0530 RazorpayNewSDK[2878:144187] [Client]
Remote object proxy returned error: Error Domain=NSCocoaErrorDomain
Code=4099 "The connection to service named
com.apple.commcenter.coretelephony.xpc was invalidated."
UserInfo={NSDebugDescription=The connection to service named
com.apple.commcenter.coretelephony.xpc was invalidated.}*

*2019-04-23 13:15:34.715384+0530 RazorpayNewSDK[2878:144049] [NetworkInfo]
Descriptors query returned error: Error Domain=NSCocoaErrorDomain Code=4099
"The connection to service named com.apple.commcenter.coretelephony.xpc was
invalidated." UserInfo={NSDebugDescription=The connection to service named
com.apple.commcenter.coretelephony.xpc was invalidated.}*

*2019-04-23 13:15:34.715649+0530 RazorpayNewSDK[2878:144187] [Client]
Sending selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099
"The connection to service named com.apple.commcenter.coretelephony.xpc was
invalidated." UserInfo={NSDebugDescription=The connection to service named
com.apple.commcenter.coretelephony.xpc was invalidated.}*

*/Users/travis/build/razorpay/razorpay-ios/RazorpayIOS/CheckoutOtpelf/Classes/RazorpayCheckoutVC.swift
deinitialized*

*2019-04-23 13:16:06.935570+0530 RazorpayNewSDK[2878:144049] Could not
signal service com.apple.WebKit.WebContent: 113: Could not find specified
service*

*2019-04-23 13:16:06.938567+0530 RazorpayNewSDK[2878:144049] Could not
signal service com.apple.WebKit.Networking: 113: Could not find specified
service*

**Comment by laralb** [comment]
any update

**Comment by jerrin15** [comment]
still getting this issue "dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /Users/admin/Library/Developer/CoreSimulator/Devices/8A820EB0-8CAE-498D-A9AE-0DD6DD5E07DB/data/Containers/Bundle/Application/49A50F69-54DA-4E36-900C-436C9DBA969D/.../Frameworks/Razorpay.framework/Razorpay
  Reason: image not found"

Using Xcode 10.1, Objective-C Project, 
Razor Pod version - 1.1.2

**Comment by pronav** [comment]
With xcode10.1, razorpay-pod 1.0.28 will work

**Comment by jerrin15** [comment]
> With xcode10.1, razorpay-pod 1.0.28 will work

Just changed to '1.0.28' now, still doesn't work. It shows the same error.

**Comment by pronav** [comment]
Let's have a remote session to debug, please add me on google hangouts: pranav@razorpay.com

**Comment by jerrin15** [comment]
It's ok I resolved it myself, Build Settings, `Always embed swift standard libraries` was NO, I changed it to YES.
