### ISSUE TITLE
/Users/travis/build/razorpay/razorpay-ios/RazorpayIOS/CheckoutOtpelf/Classes/RazorpayCheckoutVC.swift deinitialized

### ISSUE THREAD

**Issue by laralb** [razorpay/razorpay-pod#62]
- [x] I have gone through the README.(https://github.com/razorpay/razorpay-pod)
- [x] I have searched for a similar issue (https://github.com/razorpay/razorpay-pod/issues)
- [x] I am using the latest version of our framework (https://github.com/razorpay/razorpay-pod/releases)
- [x] I have cleaned my project , deleted derived data and rebuilt it.

**Comment by laralb** [comment]
i am getting swift deinitialized issue in swift 5

**Comment by nidsnitesh** [comment]
I am getting the same issue in obj-c bridge for react native. I was working earlier and i broke all of a sudden. 
`RCT_EXPORT_METHOD(startPaymentFlow:(NSString *)paymentOptions){
    dispatch_async(dispatch_get_main_queue(), ^(void){
        UIViewController *topVC = [UIApplication topViewControllerWithController:[UIApplication sharedApplication].keyWindow.rootViewController];
        razorpay = [Razorpay initWithKey:@"xxxkeyxxx-232" andDelegate:self];
        NSDictionary *options = [self stringTODict:paymentOptions];
        [razorpay open:options displayController:topVC];
    });
}`

**Comment by DominatorVbN** [comment]
I am having same issue in swift 5 razor-at team please respond @vyrazorpay @arjunnarain-rzrpay @pravinmehta-rzrpay .

**Comment by AbhinavArora95** [comment]
Hi, can you please let us know the Xcode version and the Razorpay framework version you are using.

**Comment by DominatorVbN** [comment]
Xcode 10.2
Razorpay 1.1.1

**Comment by AbhinavArora95** [comment]
Can you please explain a little further about the issue ? Are you facing a crash or is it during compile time ? I know you have mentioned about "Swift deinitialized " but please help us with the exact log / error that you are facing ?

**Comment by ashiqsulaiman93** [comment]
@AbhinavArora95 I am using xcode 10.1 and razorpay v1.0.24. The app crashes when [razorpay open:options displayController:topVC]. The only info available on the log is "swift deinitialized". Is there anything else do you want me to check ?

**Comment by sureshcapternal** [comment]
I'm getting an error for importing protocol and other Methods and Classes too. I tried both ways Manual and Pod.
I have imported
#import <Razorpay/Razorpay-Swift.h

Razorpay *razorpay; 


Error: 

> Unknown type name 'Razorpay'

**Comment by DominatorVbN** [comment]
I am having the same issue as @ashiqsulaiman93

**Comment by laralb** [comment]
> Can you please explain a little further about the issue ? Are you facing a crash or is it during compile time ? I know you have mentioned about "Swift deinitialized " but please help us with the exact log / error that you are facing ?

hi this is my sample app link please can u check. https://www.dropbox.com/s/oirlovumhq9x2t8/RazorpayNewSDK.zip?dl=0

**Comment by ashiqsulaiman93** [comment]
Did anybody find a solution to this?

**Comment by AbhinavArora95** [comment]
We are actively looking into the issue. @ashiqsulaiman93 Is your project in Objective-C or in Swift ?
@DominatorVbN Can you also please let me know the language of your project ?
@laralb We'll be looking into your project

**Comment by ashiqsulaiman93** [comment]
@AbhinavArora95 Our project is a mix of obj-c and swift. But i am trying to write a react-native bridge in obj-c. My implementation was working earlier, but it just broke all of a sudden.

**Comment by DominatorVbN** [comment]
@AbhinavArora95 my whole app is written in swift 5

**Comment by DominatorVbN** [comment]
There is this thing that razorpay working on swift 4 I mean sdk version 1.1.0 is working with swift 4.2 xcode 10.1 complier, but sdk version 1.1.1 is not working with compiler version swift 5.0 xcode 10.2

**Comment by DominatorVbN** [comment]
I can share the whole project if u want as it is gonna open source

**Comment by AbhinavArora95** [comment]
@DominatorVbN The razorpay framework 1.1.0 and 1.1.1 are both compiled in Swift 5. They should both work on Xcode 10.2 and above

**Comment by DominatorVbN** [comment]
But it is not

**Comment by DominatorVbN** [comment]
@AbhinavArora95 please go through my code I have added you as collaborator

**Comment by DominatorVbN** [comment]
hello any response??

**Comment by isha04** [comment]
@laralb call razorpay.open(options: yourOprtions, displayController: self)

**Comment by DominatorVbN** [comment]
We are doing that

**Comment by isha04** [comment]
@DominatorVbN okay. Please update when done. My work depends on this.

**Comment by DominatorVbN** [comment]
@isha04 I had used that function and now it's working correctly after updating to the latest version thanks for the help

**Comment by Adaikalraj-Sakthivel** [comment]
Hi I'm using razorpay 1.1.2 and xCode 10.2. i'm also getting the same issue. Kindly help me to come out of this issue @DominatorVbN @AbhinavArora95

**Comment by AbhinavArora95** [comment]
@Adaikalraj-Sakthivel Please use the latest framework from [here] (https://razorpay.com/docs/ios/)

**Comment by Adaikalraj-Sakthivel** [comment]
Hi @AbhinavArora95 when i tried to install latest framework this the error  shown. i had done pod repo update also still i cant install latest framework of Razorpay
![Screenshot 2019-05-06 at 4 33 30 PM](https://user-images.githubusercontent.com/47622279/57221402-be8fc880-701c-11e9-9dc6-34cf75feabb7.png)

**Comment by anshultiwari1993** [comment]
The issue still persists in my project even after installing the latest framework

/Users/travis/build/razorpay/razorpay-ios/RazorpayIOS/CheckoutOtpelf/Classes/RazorpayCheckoutVC.swift deinitialized

**Comment by OmarIbbu** [comment]
> I am having same issue in swift 5 razor-at team please respond @vyrazorpay @arjunnarain-rzrpay @pravinmehta-rzrpay .

have you got answer

**Comment by dipesh1604** [comment]
I just got the solution for the above issue and is working for me. I am working with _**Xcode 10.2**_ , _**Swift 5**_. 
I have used [razorpay-pod](https://cocoapods.org/pods/razorpay-pod) and followed [ios-standard integration](https://razorpay.com/docs/payment-gateway/ios-integration/standard/). 

Only need to change amount value grater than **100** in below example as it is mentioned that  

> **This is in currency subunits**

`internal func showPaymentForm(){
	let options: [String:Any] = [
				"amount" : "100", 
            	"description": "purchase description",
            	"image": "https://url-to-image.png",
            	"name": "business or product name",
            	"prefill": [
                	              "contact": "9797979797",
                	             "email": "foo@bar.com"
                              ],
                "theme": [
                    "color": "#F37254"
              	]
        	]
	razorpay.open(options)
}`
