### ISSUE TITLE
Xcode 10.2 error: The following binaries use incompatible versions of Swift

### ISSUE THREAD

**Issue by sivakumar-cf** [razorpay/razorpay-pod#63]
Getting the following build error on XCode 10.2.
I am using razorpay-pod version 1.1.1.

```
error: The following binaries use incompatible versions of Swift:
xxxx/Build/Products/iphonesimulator/xxx.app/Frameworks/Razorpay.framework/Razorpay
```

**Comment by GauravT9l** [comment]
Getting same issue as mentions above

**Comment by pronav** [comment]
Current version was compiled with Swift 5, is it not what you're using?

**Comment by sivakumar-cf** [comment]
Yes, I am using swift 5, compiler and i have checked the library version as well (1.1.1), which is bundled in the app frameworks.

**Comment by pronav** [comment]
Closing as resolved elsewhere: https://github.com/razorpay/react-native-razorpay/issues/177

@GauravT9l feel free to reopen if you're still facing the problem.
