### ISSUE TITLE
'Razorpay/Razorpay.h' file not found

### ISSUE THREAD

**Issue by Kashif72** [razorpay/razorpay-pod#64]
- [x] I have gone through the README.(https://github.com/razorpay/razorpay-pod)
- [x] I have searched for a similar issue (https://github.com/razorpay/razorpay-pod/issues)
- [x] I am using the latest version of our framework (https://github.com/razorpay/razorpay-pod/releases)
- [x] I have cleaned my project , deleted derived data and rebuilt it.

**Comment by Kashif72** [comment]
'Razorpay/Razorpay.h' file not found in bridging header file, I am using razorpay 1.1.2 version pod.

**Comment by pronav** [comment]
Can you try importing `<Razorpay/Razorpay-Swift.h>` instead?
see: https://github.com/razorpay/razorpay-pod#note-2

**Comment by pronav** [comment]
@Kashif72 has the issue been resolved?

**Comment by kapilSoni101** [comment]
@pronav: thanks its working....
