### ISSUE TITLE
Module compiled with Swift 5.0 cannot be imported by the Swift 4.2.1 compiler

### ISSUE THREAD

**Issue by rijaaz** [razorpay/razorpay-pod#65]
- [x] I have gone through the README.(https://github.com/razorpay/razorpay-pod)
- [x] I have searched for a similar issue (https://github.com/razorpay/razorpay-pod/issues)
- [x] I am using the latest version of our framework 

- [x] (https://github.com/razorpay/razorpay-pod/releases)

- [x] I have cleaned my project , deleted derived data and rebuilt it.

I am getting this compile time error when I was setting up an already existing project.

Module compiled with Swift 5.0 cannot be imported by the Swift 4.2.1 compiler: /xxxx/xxxx/Pods/razorpay-pod/Pod/Razorpay.framework/Modules/Razorpay.swiftmodule/x86_64.swiftmodule

## IDE Specs
Xcode version - 10.1
Razorpay - 1.1.2 installed via cocoapods.

**Comment by pronav** [comment]
Try version 1.0.28, as new version only works with xcode 10.2

**Comment by pronav** [comment]
@rijaaz does downgrading resolve the issue?
