### ISSUE TITLE
Error while creating archive

### ISSUE THREAD

**Issue by Faiyyaz** [razorpay/razorpay-pod#66]
<img width="1440" alt="Screenshot 2019-06-08 at 6 09 12 PM" src="https://user-images.githubusercontent.com/18116236/59147399-a85c9a00-8a18-11e9-8279-b26c26df8ffc.png">
- [ ] I have gone through the README.(https://github.com/razorpay/razorpay-pod)
- [ ] I have searched for a similar issue (https://github.com/razorpay/razorpay-pod/issues)
- [ ] I am using the latest version of our framework (https://github.com/razorpay/razorpay-pod/releases)
- [ ] I have cleaned my project , deleted derived data and rebuilt it.

Hi, Please find attached screenshot showing the error which I m getting while creating archive

## IDE Specs

Xcode version is 10.2
Razorpay package version is 1.3.0 custom ui

**Comment by pronav** [comment]
See following comments to solve the issue: https://github.com/razorpay/react-native-razorpay/issues/194#issuecomment-497368029

**Comment by Nautiyalsachin** [comment]
@Faiyyaz please update to the latest pod version. Also feel free to either re-open the issue or create a new issue if you have any additional queries, you can create a request [here](https://razorpay.com/support/#request).
