### ISSUE TITLE
Ra

### ISSUE THREAD

**Issue by OmarIbbu** [razorpay/razorpay-pod#67]
Razor pay checkout page is not getting displayed. Giving this error /Users/travis/build/razorpay/razorpay-ios/RazorpayIOS/CheckoutOtpelf/Classes/RazorpayCheckoutVC.swift deinitialized

**Comment by Nautiyalsachin** [comment]
@OmarIbbu, this is not giving us any information, which can help us on debugging this issue, Closing this issue for time being,   feel free to either re-open the issue or create a new issue if you have any additional queries, you can create a request [here](https://razorpay.com/support/#request).
