### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by poojab** [razorpay/razorpay-pod#68]
- [x] I have gone through the README.(https://github.com/razorpay/razorpay-pod)
- [x] I have searched for a similar issue (https://github.com/razorpay/razorpay-pod/issues)
- [x] I am using the latest version of our framework (https://github.com/razorpay/razorpay-pod/releases)
- [x] I have cleaned my project , deleted derived data and rebuilt it.

While initialising SDK getting permission denied error 

**[NetworkInfo] Signal strength query returned error: Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied", descriptor: <CTServiceDescriptor 0x2828261c0, domain=1, instance=1>**

And aftercalling open method it shows
"**/Users/travis/build/razorpay/razorpay-ios/RazorpayIOS/CheckoutOtpelf/Classes/RazorpayCheckoutVC.swift deinitialized**"

**Comment by Nautiyalsachin** [comment]
Hi @poojab, please update our plugin to the latest pod version and try again closing this issue for now. 

 Feel free to either re-open the issue or create a new issue if you have any additional queries, you can create a request [here](https://razorpay.com/support/#request).
