### ISSUE TITLE
not getting response

### ISSUE THREAD

**Issue by mohsinalimat** [razorpay/razorpay-pod#69]
Hello,

I am not getting response when I click on success or failure.

/Users/travis/build/razorpay/razorpay-ios/RazorpayIOS/CheckoutOtpelf/RazorpayCheckoutVC.swift deinitialized

**Comment by mohsinalimat** [comment]
?

**Comment by Nautiyalsachin** [comment]
Hi @mohsinalimat, closing this issue because of incomplete details, please reopen this issue or create a new issue. 

Regards, 
Sachin
