### ISSUE TITLE
Module compiled with Swift 3.1 cannot be imported in Swift 4.0.3

### ISSUE THREAD

**Issue by debugger2017** [razorpay/razorpay-pod#7]
After installing pod 'razorpay-pod', '1.0.11' I get this error **Module compiled with Swift 3.1 cannot be imported in Swift 4.0.3**. I tried deleting derived data, clean build folder also restarted Xcode. Unfortunately, none of the options worked.

**I am using Xcode version 9.2 and Swift 4.0.**

Can anyone guide me please here, what is the issue?

Thanks for helping.

**Comment by iThink32** [comment]
Hey please note that 1.0.11 is built to support Swift 3.1 and older versions of Xcode , please upgrade to Xcode 9.3 and install version 1.0.12 which is built for Swift 4.1.

**Comment by iThink32** [comment]
closing this issue , please reopen if you need any further assistance

**Comment by phadteViraj** [comment]
I'm getting this error when i switched to xcode 10
error: module compiled with Swift 4.1 cannot be imported by the Swift 4.2 compiler: /Users/viraj/Desktop/Vachan app/vachan-ios/Pods/razorpay-pod/Pod/Razorpay.framework/Modules/Razorpay.swiftmodule/x86_64.swiftmodule

**Comment by iThink32** [comment]
@phadteViraj please update to our latest framework and try.
