### ISSUE TITLE
FYI : Use   pod 'razorpay-pod', '1.0.26' with  xcode 10.1 .Please specify pod release with swfit version .

### ISSUE THREAD

**Issue by pawanline** [razorpay/razorpay-pod#70]

**Comment by Nautiyalsachin** [comment]
@pawanline, you can find the details on our [iOS plugin documentation](https://razorpay.com/docs/payment-gateway/ios-integration/standard/) and also refer the [changelogs](https://github.com/razorpay/razorpay-pod/blob/master/CHANGELOG.md) for more details.
