### ISSUE TITLE
Module compiled with Swift Error

### ISSUE THREAD

**Issue by mohsinalimat** [razorpay/razorpay-pod#71]
Hello,

Module compiled with Swift 5.0 cannot be imported by the Swift 5.1 compiler: /Pods/razorpay-pod/Pod/Razorpay.framework/Modules/Razorpay.swiftmodule/x86_64.swiftmodule

???

**Comment by pawanline** [comment]
Hello, any update on this?

**Comment by Nautiyalsachin** [comment]
We haven't release Swift 5.1 support yet, because it's not has stable release yet. If you guys want we can provide you a pre-support build.

**Comment by pawanline** [comment]
Yes, It would be really helpful for us.

**Comment by pawanline** [comment]
How will you provide the pre-support build?.

**Comment by Nautiyalsachin** [comment]
Here, you can use this line in your podfile.
```ruby
pod 'razorpay-pod', :git => 'https://github.com/razorpay/razorpay-pod.git', :branch => 'swift5.1'
```
so that you can install specific Swift 5.1 there, this is for testing purpose you can release it whenever Xcode 11 releases.

**Comment by Nautiyalsachin** [comment]
@pawanline can you give me some details about the issue?

**Comment by pawanline** [comment]
yes sure, though this issue is not related to razorpay.Its about scroll view delegate not called with release build and text field did begin editing not fired.

**Comment by Praphin** [comment]
When you guys are going to release the new version?

**Comment by shirishbankar1** [comment]
My Swift Version is set to 5.0 everywhere still I am getting this error, why ? I have installed 1.1.2 pod.

**Comment by Nautiyalsachin** [comment]
Hi, for Swift 5.0 use ```pod 'razorpay-pod', '1.1.1'```

**Comment by shirishbankar1** [comment]
@Nautiyalsachin  Tried that too(pod 'razorpay-pod', '1.1.1'). Still gives error. 
`Module compiled with Swift 5.0 cannot be imported by the Swift 5.1 compiler: /Users/Documents/ProjectName/Pods/razorpay-pod/Pod/Razorpay.framework/Modules/Razorpay.swiftmodule/arm64.swiftmodule`

**Comment by Nautiyalsachin** [comment]
@shirishbankar1, as this error is saying you are using Swift 5.1 and you have to use Swift 5.1 pod
that is - ```pod 'razorpay-pod'```
So, try to upgrade your pod to the current one. 
Let me know if the issue still persist.

**Comment by Nautiyalsachin** [comment]
try updating your whole code base to Swift 5.1

**Comment by Nautiyalsachin** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue or create a
new issue if you have any additional queries.
