### ISSUE TITLE
Razorpay custom SDK support for swift 5 and Xcode 10.2.1

### ISSUE THREAD

**Issue by commando24** [razorpay/razorpay-pod#72]
I am integrating Razorpay custom SDK with swift 5 and Xcode 10.2.1. Then i downgraded my swift version to 4.2 but still its throwing same error.

## IDE Specs
Xcode version - 10.2.1
Razerpay Custom SDK version - 1.1.3

I have cleaned my project , deleted derived data and rebuilt it. But still its throwing error.

![image](https://user-images.githubusercontent.com/15805487/62701380-c2f3c500-ba01-11e9-9b89-b6e6e11e4003.png)

**Comment by Nautiyalsachin** [comment]
Try using - 
```ruby 
pod 'razorpay-pod', '~> 1.0.26'
```

this pod version is for Swift 4.2 support.

**Comment by PatilAbhi** [comment]
Module compiled with Swift 4.2.1 cannot be imported by the Swift 5.1.3 compiler.

I am Getting this Error 

Xcode Version - 11.3.1
RazorPay SDK Version - 1.0.28
Selected Swift Version - Swift 5

Still Not able to Solve the Issue

**Comment by Nautiyalsachin** [comment]
@PatilAbhi : Try to update your Razorpay pod, by running `pod update` in your project directory. The latest pod version is `1.1.5`. If you have hardcoded it then try to update that too. 

Let me know if it works for you.

**Comment by PatilAbhi** [comment]
@Nautiyalsachin Thank You for Quick Response. It Worked. 
My Mistake was i was doing pod install. but somehow it was not installing the pod for 1.1.5 version last version was 1.1.4 it was installing .but it was not working as well. I have the way you explained and it worked Properly.

**Comment by Nautiyalsachin** [comment]
@PatilAbhi, I am glad to know that it helped 🙂. Closing the issue now.
