### ISSUE TITLE
Build success launch screen and stuck throwing following error

### ISSUE THREAD

**Issue by raghurammahathi** [razorpay/razorpay-pod#73]
- [ ] I have gone through the README.(https://github.com/razorpay/razorpay-pod)
- [ ] I have searched for a similar issue (https://github.com/razorpay/razorpay-pod/issues)
- [ ] I am using the latest version of our framework (https://github.com/razorpay/razorpay-pod/releases)
- [ ] I have cleaned my project , deleted derived data and rebuilt it.

## IDE Specs
 swift5.0 compiled version

**Comment by raghurammahathi** [comment]
dyld: Symbol not found: _OBJC_CLASS_$__TtCs12_SwiftObject
  Referenced from: /Users/raghurammahathi/Library/Developer/CoreSimulator/Devices/88AC5A7C-8B5B-4BD8-B690-3A14DBFC283B/data/Containers/Bundle/Application/14D0ED4A-6AC4-4BFB-B834-D113D533B076//Frameworks/Razorpay.framework/Razorpay
  Expected in: /Users/raghurammahathi/Library/Developer/CoreSimulator/Devices/88AC5A7C-8B5B-4BD8-B690-3A14DBFC283B/data/Containers/Bundle/Application/14D0ED4A-6AC4-4BFB-B834-D113D533B076/1ounceapp/Frameworks/libswiftCore.dylib
 in /Users/raghurammahathi/Library/Developer/CoreSimulator/Devices/88AC5A7C-8B5B-4BD8-B690-3A14DBFC283B/data/Containers/Bundle/Application/14D0ED4A-6AC4-4BFB-B834-D113D533B076//Frameworks/Razorpay.framework/Razorpay

**Comment by manoj-bht** [comment]
I am also having the same issue with latest Razorpay Standard SDK 1.2.1 and Swift 5.0.1

dyld: Symbol not found: _OBJC_CLASS_$__TtCs12_SwiftObject
  Referenced from: /Users/apple/Library/Developer/CoreSimulator/Devices/DDDD929D-94E9-49DE-8A15-A117DE239A1A/data/Containers/Bundle/Application/E04C3C7E-AD0B-4167-8F8A-8E3A3C46A2A9/Wealth Status.app/Frameworks/Razorpay.framework/Razorpay
  Expected in: /Library/Developer/Toolchains/swift-5.0.1-RELEASE.xctoolchain/usr/lib/swift/iphonesimulator/libswiftCore.dylib
 in /Users/apple/Library/Developer/CoreSimulator/Devices/DDDD929D-94E9-49DE-8A15-A117DE239A1A/data/Containers/Bundle/Application/E04C3C7E-AD0B-4167-8F8A-8E3A3C46A2A9/Wealth Status.app/Frameworks/Razorpay.framework/Razorpay
(lldb) 

Please help me if any workaround here.

**Comment by Nautiyalsachin** [comment]
Hey @raghurammahathi, @manoj-bht : Please update the pod to latest version. 

For now closing this issue, feel free to either re-open the issue or create a new issue if you have any additional queries.
