### ISSUE TITLE
ITMS-90809: Deprecated API Usage UIWebView

### ISSUE THREAD

**Issue by ashish-meesho** [razorpay/razorpay-pod#74]
- [ ] I have gone through the README.(https://github.com/razorpay/razorpay-pod)
- [ ] I have searched for a similar issue (https://github.com/razorpay/razorpay-pod/issues)
- [ ] I am using the latest version of our framework (https://github.com/razorpay/razorpay-pod/releases)
- [ ] I have cleaned my project , deleted derived data and rebuilt it.

## Screenshots 

While submitting my app to app store. I got the following email from Apple, and due to which we can have the issue in submitting App to store.

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

**Comment by Nautiyalsachin** [comment]
Hi @ashish-meesho, we have already addressed this in our earlier releases, still asking you to upgrade to the latest pod version,

For now closing this issue, feel free to either re-open or create a new issue if you have any additional queries.
