### ISSUE TITLE
Xcode 11 Razor pay error while archiving - URGENT!

### ISSUE THREAD

**Issue by Praphin** [razorpay/razorpay-pod#75]
<img width="751" alt="Screenshot 2019-09-23 at 10 29 42 PM" src="https://user-images.githubusercontent.com/6714897/65446303-b01e3e00-de51-11e9-8ae4-ce1ee40020d5.png">

**Comment by Pawanpreet93** [comment]
Facing the same issue. 

Logs- IDEDistributionItem init <DVTFilePath:0x7ffd55a36db0:'/Users/pawanpreetsingh/Library/Developer/Xcode/Archives/2019-09-24/Zolo-iOS 24-09-19, 12.27 AM.xcarchive/Products/Applications/Zolo-iOS.app/Frameworks/Razorpay.framework/Frameworks/Pods_CheckoutOtpelf.framework'>

**Comment by KarthickBE** [comment]
Error on archive the iOS Project.
Found an unexpected Mach-O header code: 0x72613c21
![Screenshot 2019-09-24 at 7 04 18 AM](https://user-images.githubusercontent.com/28004704/65474475-a02a4c80-de99-11e9-952f-45f535ef9d09.png)

**Comment by aravindcraj** [comment]
Hey @pronav, Can you help us solving this issue?

**Comment by Nautiyalsachin** [comment]
Can you try using 
```
pod 'razorpay-pod', :git => 'https://github.com/razorpay/razorpay-pod.git', :branch => '0x72613c21'
```

**Comment by karthick-ck-ios** [comment]
@Nautiyalsachin  Still I am facing the same issue.

**Comment by Nautiyalsachin** [comment]
@karthick-ck-ios  have you updated your pods ?

For updating pods run - ```pod update```

**Comment by karthick-ck-ios** [comment]
Could not find a storyboard named 'Checkout' in bundle NSBundle

**Comment by karthick-ck-ios** [comment]
> Trying to fix it, for now you can skip pods addition and download framework from https://razorpay.com/docs/payment-gateway/ios-integration/standard/.

@Nautiyalsachin Standard Integration also having the same error.
Found an unexpected Mach-O header code: 0x72613c21

**Comment by Nautiyalsachin** [comment]
Have fixed issue with this pod

```
pod 'razorpay-pod', :git => 'https://github.com/razorpay/razorpay-pod.git',  :branch => 'swift5.1'
```

Also do update pod afterwards, ``` pod update```

Let me know if it works for you.

**Comment by karthick-ck-ios** [comment]
@Nautiyalsachin  Working fine, Thanks.

**Comment by Praphin** [comment]
It Worked. Thanks

**Comment by Coppercodes1** [comment]
> pod 'razorpay-pod', :git => 'https://github.com/razorpay/razorpay-pod.git',  :branch => 'swift5.1'

I am getting following error and pod is not getting installed:
CocoaPods could not find compatible versions for pod "razorpay-pod":
  In Podfile:
    razorpay-pod (from `https://github.com/razorpay/razorpay-pod.git`, branch `swift5.1`)

Specs satisfying the `razorpay-pod (from `https://github.com/razorpay/razorpay-pod.git`, branch `swift5.1`)` dependency were found, but they required a higher minimum deployment target.

**Comment by mbhansali** [comment]
Kindly update Razorpay for XCode 11 on Cococapods.
On Cocoapods still have old version which only support xcode 10.2.

**Comment by maskedTitan** [comment]
@mbhansali You can visit: https://cocoapods.org/pods/razorpay-pod to find the latest version of our pod v1.1.4 that is compatible with Xcode 11.

**Comment by SandipSerantec** [comment]
> > pod 'razorpay-pod', :git => 'https://github.com/razorpay/razorpay-pod.git',  :branch => 'swift5.1'
> 
> I am getting following error and pod is not getting installed:
> CocoaPods could not find compatible versions for pod "razorpay-pod":
> In Podfile:
> razorpay-pod (from `https://github.com/razorpay/razorpay-pod.git`, branch `swift5.1`)
> 
> Specs satisfying the `razorpay-pod (from `[https://github.com/razorpay/razorpay-pod.git`](https://github.com/razorpay/razorpay-pod.git%60), branch `swift5.1`)` dependency were found, but they required a higher minimum deployment target.

Fix issue
Thanks Team

**Comment by SandipSerantec** [comment]
> Have fixed issue with this pod
> 
> ```
> pod 'razorpay-pod', :git => 'https://github.com/razorpay/razorpay-pod.git',  :branch => 'swift5.1'
> ```
> 
> Also do update pod afterwards, ` pod update`
> 
> Let me know if it works for you.

 Thans you Nautiyalsachin

**Comment by Nautiyalsachin** [comment]
Please always use our latest pod 'razorpay-pod' instead of any branch, this will help you to be updated with the latest releases and bug fixes.
