### ISSUE TITLE
Error On Xcode 11.1 

### ISSUE THREAD

**Issue by prashanth-icliniq** [razorpay/razorpay-pod#77]
Module compiled with Swift 5.0 cannot be imported by the Swift 5.1 compiler: /Users/XXXXXX/Pods/razorpay-pod/Pod/Razorpay.framework/Modules/Razorpay.swiftmodule/arm64.swiftmodule

**Comment by Praphin** [comment]
try this
**pod 'razorpay-pod', :git => 'https://github.com/razorpay/razorpay-pod.git', :branch => '0x72613c21'**

**Comment by prashanth-icliniq** [comment]
ok Sir i try and Message you

Prashanth T D
IOS Developer
www.icliniq.com <https://www.icliniq.com/?utm_campaign=mail_sign_internal>

**Comment by prashanth-icliniq** [comment]
This on not working still loading am waiting Half hour

Prashanth T D
IOS Developer
www.icliniq.com <https://www.icliniq.com/?utm_campaign=mail_sign_internal>

**Comment by prashanth-icliniq** [comment]
Hello sir,
 now its working fine

Thanks

Prashanth T D
IOS Developer
www.icliniq.com <https://www.icliniq.com/?utm_campaign=mail_sign_internal>
