### ISSUE TITLE
Crash when razorpay.open second time.

### ISSUE THREAD

**Issue by O-mkar** [razorpay/razorpay-pod#78]
- [X] I have gone through the README.(https://github.com/razorpay/razorpay-pod)
- [X] I have searched for a similar issue (https://github.com/razorpay/razorpay-pod/issues)
- [X] I am using the latest version of our framework (https://github.com/razorpay/razorpay-pod/releases)
- [X] I have cleaned my project , deleted derived data and rebuilt it.

the second time when I run function **razorpay.open** it crashes.

```
 func showPaymentForm(){
        let options: [String:Any] = [
                    "amount": "100", //This is in currency subunits. 100 = 100 paise= INR 1.
                    "currency": "INR",//We support more that 92 international currencies.
                    "description": "purchase description",
                    "order_id": "order_DMnnq4okfdOVVF",
                    "image": "https://url-to-image.png",
                    "name": "Test",
                    "prefill": [
                        "contact": "9797979797",
                        "email": "foo@bar.com"
                    ],
                    "theme": [
                        "color": "#F37254"
                    ]
                ]
        
        razorpay.open(options, display: self.navigationController ?? UINavigationController())
    }
```
## IDE Specs
XCode 11.0
razorpay-pod 1.1.2

## Retro Steps
1) On button, click open the payment page with razorpay.open.
2) Click the close button which will cancel the payment.
3) Now try again opening the payment page with a button click, it should crash.

## Screenshots 

![Screenshot 2019-09-28 at 9 12 15 AM](https://user-images.githubusercontent.com/16367429/65811031-1eeff400-e1d0-11e9-859d-25c7ca786a8c.png)

**Comment by mohsinalimat** [comment]
Remove order_id from main dict and put below code.

let options: [String:Any] = [
                    "amount": "100", //This is in currency subunits. 100 = 100 paise= INR 1.
                    "currency": "INR",//We support more that 92 international currencies.
                    "description": "purchase description",
                    "image": "https://url-to-image.png",
                    "name": "Test",
                    "prefill": [
                        "contact": "9797979797",
                        "email": "foo@bar.com"
                    ],
                    "notes": [
                         "order_id": "order_DMnnq4okfdOVVF",
                     ],
                    "theme": [
                        "color": "#F37254"
                    ]
                ]

**Comment by O-mkar** [comment]
> let options: [String:Any] = [
> "amount": "100", //This is in currency subunits. 100 = 100 paise= INR 1.
> "currency": "INR",//We support more that 92 international currencies.
> "description": "purchase description",
> "image": "https://url-to-image.png",
> "name": "Test",
> "prefill": [
> "contact": "9797979797",
> "email": "[foo@bar.com](mailto:foo@bar.com)"
> ],
> "notes": [
> "order_id": "order_DMnnq4okfdOVVF",
> ],
> "theme": [
> "color": "#F37254"
> ]
> ]

Still Crashes, Its always the second time

**Comment by mohsinalimat** [comment]
[[1fqm6s]]Mohsinali Matiya sent you an Encrypted Message on Spike

[[[1fqm6s]]View Message on Spike >](https://gethop.com/secure/openapp/?mid=c-b6be-k17b8uli-kpnt0w)

[[1fqm6s]](https://gethop.com/secure/openapp/?mid=c-b6be-k17b8uli-kpnt0w)

**Comment by Nautiyalsachin** [comment]
Looks like you guys have sorted this out, Thanks @mohsinalimat, for the help here. 

closing this issue now, feel free to either re-open the issue or create a new issue if you have any additional queries.
