### ISSUE TITLE
Razorpay custom SDK not support in Xcode 11

### ISSUE THREAD

**Issue by iCoderzDev** [razorpay/razorpay-pod#81]
I am integrating Razorpay custom SDK in swift 5 and Xcode  11. But showing error I have attach screenshots.

## IDE Specs
Razorpay Custom UI 1.3.0
Xcode : 11
Swift : 5

## Screenshots 
![Screenshot 2019-10-10 at 2 21 29 PM](https://user-images.githubusercontent.com/26161402/66553739-4ac48f80-eb69-11e9-8055-f0bc38877bfd.png)

**Comment by Nautiyalsachin** [comment]
@iCoderzDev For swift 5 support use,
```
pod 'razorpay-pod', '1.1.2'
```

**Comment by iCoderzDev** [comment]
@Nautiyalsachin Not working facing same error. 


![Screenshot 2019-10-10 at 3 44 19 PM](https://user-images.githubusercontent.com/26161402/66560347-da237000-eb74-11e9-853d-beb2f3ec20d8.png)

**Comment by Nautiyalsachin** [comment]
@iCoderzDev  try for 
```
pod 'razorpay-pod', '1.1.1'
```

**Comment by iCoderzDev** [comment]
@Nautiyalsachin  Not working

![Screenshot 2019-10-10 at 4 28 11 PM](https://user-images.githubusercontent.com/26161402/66563249-06da8600-eb7b-11e9-8a04-8565ecbf0966.png)

**Comment by Nautiyalsachin** [comment]
What error are you getting now ?

**Comment by iCoderzDev** [comment]
Same error.

**Comment by Nautiyalsachin** [comment]
@iCoderzDev  Razorpay-Pod 1.1.1 supports Swift 5.0 as I can see it in **Razorpay-Swift.h** inside Razorpay.framework. Also please try to change the current language to Swift 5.1 from Build Settings as Xcode 11 have Swift 5.1 by default.

**Comment by iCoderzDev** [comment]
Hello. @Nautiyalsachin 

I am install new Razorpay Framework "Razorpay Custom UI 1.3.1" and the previous issues is solved thank you. But I am facing new error  "Could not find module 'Razorpay' for target 'x86_64-apple-ios-simulator'; found: arm64, armv7-apple-ios, arm64-apple-ios, arm, armv7"  this error is only showing to run my project in simulato. it's working in device perfectly. 

 I am attach one screenshots please check.

![Screenshot 2019-10-14 at 12 16 45 PM](https://user-images.githubusercontent.com/26161402/66733292-b0bc5a00-ee7c-11e9-9b1b-76f6faf7b77e.png)

**Comment by Nautiyalsachin** [comment]
You are using a run script which is removing iOS Simulator architecture, please comment it and run your project, also you have to uncomment it before submitting it to the App Store.

**Comment by iCoderzDev** [comment]
no I am not using any run script. 

and which run scrip are add to uploading Time 
https://stackoverflow.com/questions/42641806/check-and-remove-unsupported-architecture-x86-64-i386-in-ipa-archive

**Comment by iCoderzDev** [comment]
Hello. @Nautiyalsachin

I am install new Razorpay Framework "Razorpay Custom UI 1.3.1"  and I am run app in device so facing this error " dyld: Library not loaded: @rpath/Razorpay.framework/Razorpay "  Reason: image not found. and app is crash.

**Comment by Nautiyalsachin** [comment]
Try downloading the new Custom UI 1.3.2 SDK. Also change embed to "Embed & Sign" in General.

**Comment by iCoderzDev** [comment]
Thank you @Nautiyalsachin it's working perfectly run. but still I am run in simulator then I am facing this error. "Could not find module 'Razorpay' for target 'x86_64-apple-ios-simulator'; found: arm64, armv7-apple-ios, arm64-apple-ios, arm, armv7"
