### ISSUE TITLE
RazorpayCheckoutWebView deinitialized Xcode 11

### ISSUE THREAD

**Issue by aksh1995** [razorpay/razorpay-pod#82]
- [x] I have gone through the README.(https://github.com/razorpay/razorpay-pod)
- [x] I have searched for a similar issue (https://github.com/razorpay/razorpay-pod/issues)
- [x] I am using the latest version of our framework (https://github.com/razorpay/razorpay-pod/releases)
- [x] I have cleaned my project , deleted derived data and rebuilt it.

I have upgraded to all the latest version of Xcode and razorpay 

I am not able to pay after using the new documentation
            razorpay.open(options, display: self)
            razorpay.open(options) with web view both give out the same error 

ERROR LOG

<UINavigationController: 0x7fbb3f06e800> which is already presenting <UINavigationController: 0x7fbb3e968800>
/Users/sachinnautiyal/Documents/Razorpay/razorpay-ios/RazorpayIOS/CheckoutOtpelf/Classes/RazorpayCheckoutVC.swift deinitialized
/Users/sachinnautiyal/Documents/Razorpay/razorpay-ios/RazorpayIOS/CheckoutOtpelf/Classes/RazorpayCheckoutWebView.swift:["/Users/sachinnautiyal/Documents/Razorpay/razorpay-ios/RazorpayIOS/CheckoutOtpelf/Classes/RazorpayCheckoutWebView.swift deinitialized"]

how do I solve this I am not able to push and update as this is not working

**Comment by Nautiyalsachin** [comment]
Can you give me more details :-
1. From where are you executing **razorpay.open(options)**? If it is from **ViewDidLoad()** then change it to **ViewDidAppear()**. else please give me more details about how you are trying to present it. 
2. Also include which pod version are you using?

**Comment by aksh1995** [comment]
hey, I am using Razorpay Standard SDK 1.2.1
and I tried in both ViewDidAppear() and ViewDidLoad() 
I used web view to open and the view opens and closes and comes back to older vc where we ask for users upi id

**Comment by aksh1995** [comment]
["currency": "INR", "amount": 100, "order_id": "order_DTqYDarwWXEMzH", "email": "****@gmail.com", "contact": "904*******", "vpa": "**********", "method": "upi"]

this is the options attached in the razorpay.open function

**Comment by Nautiyalsachin** [comment]
Hi @aksh1995, Can you create a sample app and share the Github url here? I am still unable to figure out the issue.

**Comment by aksh1995** [comment]
[test.zip](https://github.com/razorpay/razorpay-pod/files/3723290/test.zip)
I have uploaded here reproducing the error

**Comment by aksh1995** [comment]
I tried using             razorpay.open(options, display: self)

this was the error log------

/Users/sachinnautiyal/Documents/Razorpay/razorpay-ios/RazorpayIOS/CheckoutOtpelf/Classes/InternalRazorpay.swift:["payment failed"]
/Users/sachinnautiyal/Documents/Razorpay/razorpay-ios/RazorpayIOS/CheckoutOtpelf/Classes/RazorpayCheckoutVC.swift deinitialized
/Users/sachinnautiyal/Documents/Razorpay/razorpay-ios/RazorpayIOS/CheckoutOtpelf/Classes/RazorpayCheckoutWebView.swift:["/Users/sachinnautiyal/Documents/Razorpay/razorpay-ios/RazorpayIOS/CheckoutOtpelf/Classes/RazorpayCheckoutWebView.swift deinitialized"]

**Comment by Nautiyalsachin** [comment]
Hi, there are some things which I've noticed that doesn't look right: - 

1. Options are looked as you are using Custom SDK not the Standard SDK, please verify your options again. 

2. Remove WebKit from your code as its only applicable for Custom SDK (You are using pods and pods are available only for Standard SDK). refer the Razorpay iOS documentation (https://razorpay.com/docs/payment-gateway/ios-integration/) for more details.

3. I am getting logs in success method that is giving output as "Payment Failed - Unexpected Error"

4. Order_id is giving me error that it's not valid after debugging it more. Please try to remove it and try again. We are working on it and right now you can proceed it without the Order_id field.

Let me know if anything doesn't look right or you need more clarification.

**Comment by aksh1995** [comment]
hey sorry for the inconvenience I should have followed with standard sdk now when I do UPI collect request it give paymentMode is empty error

**Comment by aksh1995** [comment]
thanks for your help solved it!!

**Comment by aksh1995** [comment]
hey I got the same error in the device iPhone XR running with iOS version
13.1.2

the order id was order_Df2ZDBm57oiF6P

what is causing this error????

the user is not able to make payment for past couple of weeks
