### ISSUE TITLE
Razorpay UPI collect request custom sdk

### ISSUE THREAD

**Issue by aksh1995** [razorpay/razorpay-pod#83]
![Screenshot 2019-10-15 at 10 39 28 AM](https://user-images.githubusercontent.com/56014243/66801908-597bbf80-ef38-11e9-8d61-afb8ac8a9b35.png)
- [x] I have gone through the README.(https://github.com/razorpay/razorpay-pod)
- [x] I have searched for a similar issue (https://github.com/razorpay/razorpay-pod/issues)
- [x] I am using the latest version of our framework (https://github.com/razorpay/razorpay-pod/releases)
- [x] I have cleaned my project , deleted derived data and rebuilt it.

RazorpaySuccessResponse(status: "error", code: "4220", message: Optional("paymentMode Cannot be empty"))

I am getting error when I do **razorpay.authorize(options)**

and am sending all these which was in documentation
let options: [AnyHashable:Any] = [
                "amount": "100", // amount in paise
                "currency": "INR",
                "email": "a@b.com",
                "contact": "1234567890",
                "method":"upi",
                "vpa":"test@axisbank"
            ]
            self.razorpay?.authorize(options)

**Comment by aksh1995** [comment]
and I couldn't find any payment mode in documentation

**Comment by aksh1995** [comment]
this is delaying our update can u help out asap!

**Comment by aksh1995** [comment]
hey I got the same error in the device iPhone XR running with iOS version 13.1.2

the order id was order_Df2ZDBm57oiF6P

what is causing this error 

the user is not able to make payment for past couple of weeks

**Comment by Nautiyalsachin** [comment]
Please check your order id. You can verify this without sending order id.

**Comment by aksh1995** [comment]
Hey ,the same code works for other mobiles and in dashboard it is showing
that the payment failed and error "payment mode cannot be empty",
but the same method used for other users and device is still working fine

and another case when i tried doing an upi collect request first time it
failed and then i tried twice i was able to pay and this was live version
of the app and the codes were not changed,why does it fail randomly ?? and
how do we solve this issue

**Comment by Nautiyalsachin** [comment]
Hi @aksh1995, Try with a new Order id, please update the plugin to the latest version, 

For now closing this issue, feel free to either re-open the issue or create a new issue if you have any additional queries.
