### ISSUE TITLE
white blank screen : swift 5.1  | pod 'razorpay-pod' | "react-native-razorpay": "^2.1.31"

### ISSUE THREAD

**Issue by cullsin** [razorpay/razorpay-pod#85]
- [ ] I have gone through the README.(https://github.com/razorpay/razorpay-pod)
- [ ] I have searched for a similar issue (https://github.com/razorpay/razorpay-pod/issues)
- [ ] I am using the latest version of our framework (https://github.com/razorpay/razorpay-pod/releases)
- [ ] I have cleaned my project , deleted derived data and rebuilt it.

after I installed and integrated with pod. I am getting a blank white screen. bundle is not started and index.js is not getting triggered. I did not see any error messages. when I uninstall razorpay, my app is loaded successfully.

## IDE Specs
I am using react native.

## Screenshots 
![image](https://user-images.githubusercontent.com/5137598/68968011-89ec9d00-0807-11ea-8567-4d6e6e2c40df.png)

**Comment by Nautiyalsachin** [comment]
Please update your react-native-razorpay plugin, it's been fixed. Also, update podfile if you haven't updated it yet. 

Feel free to open this issue.
