### ISSUE TITLE
Module compiled with Swift 5.0 cannot be imported by the Swift 5.1.2 compiler: /Users/sailaja/Desktop/Eemos/Pods/razorpay-pod/Pod/Razorpay.framework/Modules/Razorpay.swiftmodule/arm64.swiftmodule

### ISSUE THREAD

**Issue by kingglov** [razorpay/razorpay-pod#86]
- [x] I have gone through the README.(https://github.com/razorpay/razorpay-pod)
- [x] I have searched for a similar issue (https://github.com/razorpay/razorpay-pod/issues)
- [x] I am using the latest version of our framework (https://github.com/razorpay/razorpay-pod/releases)
- [x] I have cleaned my project , deleted derived data and rebuilt it.

Module compiled with Swift 5.0 cannot be imported by the Swift 5.1.2 compiler: /Users/sailaja/Desktop/Eemos/Pods/razorpay-pod/Pod/Razorpay.framework/Modules/Razorpay.swiftmodule/arm64.swiftmodule

**Comment by kingglov** [comment]
error while importing to viewController 

Module compiled with Swift 5.0 cannot be imported by the Swift 5.1.2 compiler: /Users/sailaja/Desktop/Eemos/Pods/razorpay-pod/Pod/Razorpay.framework/Modules/Razorpay.swiftmodule/arm64.swiftmodule

**Comment by kingglov** [comment]
i've made it by replacing  this pod 'razorpay-pod','~> 1.1.1' with pod 'razorpay-pod'

**Comment by PatilAbhi** [comment]
Module compiled with Swift 4.2.1 cannot be imported by the Swift 5.1.3 compiler.

I am Getting this Error

Xcode Version - 11.3.1
RazorPay SDK Version - 1.0.28
Selected Swift Version - Swift 5

Still Not able to Solve the Issue
