### ISSUE TITLE
error: The following binaries use incompatible versions of Swift:

### ISSUE THREAD

**Issue by nikhil191090** [razorpay/razorpay-pod#87]
error: The following binaries use incompatible versions of Swift:
/Users/XXX/Library/Developer/Xcode/DerivedData/XXXX-faupqapevobuuzexpujrjtfkhuio/Build/Products/Debug-iphoneos/XXXX.app/Frameworks/Razorpay.framework/Razorpay

i am getting this issue i am using xcode 11.2.1 with swift 4.2 and i installed pod 'razorpay-pod', '~> 1.0.26' 

Please Help

**Comment by maskedTitan** [comment]
Hi Nikhil, 

You seem to be using an older version of our pod. Please install the latest pod of Razorpay v1.1.4 from [here](https://cocoapods.org/pods/razorpay-pod)

**Comment by nikhil191090** [comment]
@maskedTitan Thank you for your help. It's working !!
