### ISSUE TITLE
Razor pay ios implementation issue

### ISSUE THREAD

**Issue by ayushP2400** [razorpay/razorpay-pod#90]
- [x] I have gone through the README.(https://github.com/razorpay/razorpay-pod)
- [x] I have searched for a similar issue (https://github.com/razorpay/razorpay-pod/issues)
- [x] I am using the latest version of our framework (https://github.com/razorpay/razorpay-pod/releases)
- [x] I am gone through the FAQ's (https://github.com/razorpay/razorpay-pod/wiki/FAQ's)
- [x] I have cleaned my project , deleted derived data and rebuilt it.

getting error:-

/Users/sachinnautiyal/Documents/Razorpay/razorpay-ios/RazorpayIOS/CheckoutOtpelf/Classes/InternalRazorpay.swift:["payment failed"]
/Users/sachinnautiyal/Documents/Razorpay/razorpay-ios/RazorpayIOS/CheckoutOtpelf/Classes/RazorpayCheckoutVC.swift deinitialized
/Users/sachinnautiyal/Documents/Razorpay/razorpay-ios/RazorpayIOS/CheckoutOtpelf/Classes/RazorpayCheckoutWebView.swift:["/Users/sachinnautiyal/Documents/Razorpay/razorpay-ios/RazorpayIOS/CheckoutOtpelf/Classes/RazorpayCheckoutWebView.swift deinitialized"]

## IDE Specs

xcode 11

Razorpay Standard SDK 1.2.1 

## Retro Steps
let options: [String:Any] = [
                    "amount": price, //This is in currency subunits. 100 = 100 paise= INR 1.
                    "currency": "INR",//We support more that 92 international currencies.
                    "description": "purchase description",
                    "order_id": self.txnId,
                    "image": "",
                    "name": "ewfd",
                    "prefill": [
                        "contact": "\(login_model.shared.user_mobile)",
                        "email": "\(login_model.shared.user_email)"
                    ],
                    "theme": [
                        "color": "#212038"
                    ]
                ]
     
        DispatchQueue.main.async {
            self.razorpay.open(options, display: self)
        }

## Screenshots 

[RPReplay_Final1581932266.MP4.zip](https://github.com/razorpay/razorpay-pod/files/4212892/RPReplay_Final1581932266.MP4.zip)

**Comment by Nautiyalsachin** [comment]
Hi @ayushP2400, can you try it without an order id? If it works without order id then check your order id logic again.  Also validate your Razorpay key, is that correct or not.

**Comment by Nautiyalsachin** [comment]
Closing this issue due to the time elapsed. 

Please feel free to either re-open the issue or create a new issue if you have any additional queries.

**Comment by Swapna67m** [comment]
check your razorpay key. it may be expired.

**Comment by nimishaJoshy** [comment]
> Hi @ayushP2400, can you try it without an order id? If it works without order id then check your order id logic again. Also validate your Razorpay key, is that correct or not.

worked for me on Jul 28 th 2021.
