### ISSUE TITLE
Support Swift 5.2 Compiler

### ISSUE THREAD

**Issue by abhuzz** [razorpay/razorpay-pod#91]
- [✔️] I have gone through the README.(https://github.com/razorpay/razorpay-pod)
- [✔️] I have searched for a similar issue (https://github.com/razorpay/razorpay-pod/issues)
- [✔️] I am using the latest version of our framework (https://github.com/razorpay/razorpay-pod/releases)
- [✔️] I am gone through the FAQ's (https://github.com/razorpay/razorpay-pod/wiki/FAQ's)
- [✔️] I have cleaned my project, deleted derived data and rebuilt it.

Pod not support swift 5.2 in XCode 11.4 
## IDE Specs

Xcode Version :- 11.4
Razorpay Package Version :- latest version 
## Retro Steps

Step 1: install Pod with:- pod 'razorpay-pod'
          Result: not support 
Step 2: install pod with:- pod 'razorpay-pod' , :git => 'https://github.com/razorpay/razorpay-pod.git', :branch => 'swift5.2'
         Result: 'Razorpay' is unavailable: cannot find Swift declaration for this class
SO, I fond that this rezorpay-pod can't support to swift 5.2 

Kindly request the developer team enable support for Swift5.2 Compiler.

## Screenshots 

  
![image](https://user-images.githubusercontent.com/6681394/77749903-dadb9000-7048-11ea-9b35-445dd6209463.png)

![image](https://user-images.githubusercontent.com/6681394/77751975-b1246800-704c-11ea-8e59-f098f9844018.png)

**Comment by kevintorch** [comment]
I have the same issue.

**Comment by kevintorch** [comment]
> * [✔️] I have gone through the README.(https://github.com/razorpay/razorpay-pod)
> * [✔️] I have searched for a similar issue (https://github.com/razorpay/razorpay-pod/issues)
> * [✔️] I am using the latest version of our framework (https://github.com/razorpay/razorpay-pod/releases)
> * [✔️] I am gone through the FAQ's (https://github.com/razorpay/razorpay-pod/wiki/FAQ's)
> * [✔️] I have cleaned my project, deleted derived data and rebuilt it.
> 
> Pod not support swift 5.2 in XCode 11.4
> 
> ## IDE Specs
> Xcode Version :- 11.4
> Razorpay Package Version :- latest version
> 
> ## Retro Steps
> Step 1: install Pod with:- pod 'razorpay-pod'
> Result: not support
> Step 2: install pod with:- pod 'razorpay-pod' , :git => 'https://github.com/razorpay/razorpay-pod.git', :branch => 'swift5.2'
> Result: 'Razorpay' is unavailable: cannot find Swift declaration for this class
> SO, I fond that this rezorpay-pod can't support to swift 5.2
> 
> Kindly request the developer team enable support for Swift5.2 Compiler.
> 
> ## Screenshots
> ![image](https://user-images.githubusercontent.com/6681394/77749903-dadb9000-7048-11ea-9b35-445dd6209463.png)
> 
> ![image](https://user-images.githubusercontent.com/6681394/77751975-b1246800-704c-11ea-8e59-f098f9844018.png)

Sir, Did you find any solution related to this?

**Comment by kevintorch** [comment]
@abhuzz Sir, did you find any solution related to this?

**Comment by Nautiyalsachin** [comment]
Hi Everyone, we are working on releasing an updated version of the pod in the next couple of days, the new changes are in testing right now. 

I'll inform you guys As soon as the changes are live.

**Comment by Nautiyalsachin** [comment]
Can you guys use `pod 'razorpay-pod', :git => 'https://github.com/razorpay/razorpay-pod.git', :branch => 'Swift_5.2'`

**Comment by abhuzz** [comment]
@Nautiyalsachin Sir, Thank You for the kind response. 
Now, the problem is "**Use of undeclared type 'Razorpay'** " for the following sentence : -
`var razorpay: Razorpay!`
- I faced this issue in the new branch 'swift_5.2'
![image](https://user-images.githubusercontent.com/6681394/77992739-4ae95f00-7344-11ea-9ed7-3774a249aba9.png)

Implemented with branch => 'swift_5.2'
![image](https://user-images.githubusercontent.com/6681394/77992952-bf240280-7344-11ea-8323-644529ba2706.png)

and having a swift version like =>
![image](https://user-images.githubusercontent.com/6681394/77995660-e03b2200-7349-11ea-82db-c00c2d96e057.png)

- Please, Suggest if I forget to put something in code.

**Comment by kevintorch** [comment]
@abhuzz it's **RazorpayCheckout** Now not **Razorpay** from now on.

**Comment by kevintorch** [comment]
@abhuzz Change the type from **Razorpay** to **RazorpayCheckout**

**Comment by abhuzz** [comment]
@kevintorch  Thanks.

**Comment by Nautiyalsachin** [comment]
Great! You guys have figured it out already. 🙂 Can you try to archive it and let me know that it's working fine for you or not? I'll then try to release it by today itself?

If you don't want to change anything in your code you can use below code - 

For swift `// typealias Razorpay = RazorpayCheckout`
For Objective C `//- typedef RazorpayCheckout Razorpay;`
