### ISSUE TITLE
Use of undeclared type 'Razorrpay'

### ISSUE THREAD

**Issue by patelvivek9115** [razorpay/razorpay-pod#98]
## Description

I have a project with integration of Razorpay on razorpay-pod (1.1.1)  without any issue (last time I checked in Feb 2020), now today I need to make some changes and provide an updated build to my client but suddenly I am getting an error saying Use of undeclared type 'Razorpay'. So I updated the pod and the latest one I installed is razorpay-pod (1.1.5) but still getting the same error. I also tried with the example project provided by git but that one also has the same issue. Could you please check and get back to me ASAP.
Thanks

## Razorpay pod Version :
1.1.5

## Xcode Version :
11.5

### What you did:

I have updated the razorpay-pod version from 1.1.1 to 1.1.5

### What happened:

Use of undeclared type 'Razorrpay' ()

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. You can download the github example project and find that issue

### Suggested solution:
No idea

## Code example, screenshot, or link to a repository:

<img width="829" alt="Screenshot 2020-07-07 at 2 55 41 PM" src="https://user-images.githubusercontent.com/14240280/86759206-00bdfb00-c062-11ea-81ed-54c5fb3dffe4.png">

<img width="1084" alt="Screenshot 2020-07-07 at 2 44 47 PM" src="https://user-images.githubusercontent.com/14240280/86759396-21865080-c062-11ea-9f38-e2978c04c575.png">

import Razorpay

class CheckoutVC: BaseViewController {    
    var razorpay: Razorrpay!
}

**Comment by Nautiyalsachin** [comment]
@patelvivek9115 : Where is the Github link?

**Comment by patelvivek9115** [comment]
@Nautiyalsachin : Which Github link you are talking about?

**Comment by ambujap94** [comment]
Please use 
var razorpay: Razorpay!
instead of
var razorpay: Razorrpay!

**Comment by patelvivek9115** [comment]
> Please use
> var razorpay: Razorpay!
> instead of
> var razorpay: Razorrpay!
> 
> you can follow the document here https://razorpay.com/docs/payment-gateway/ios-integration/standard/

I have tried this "var razorpay: Razorpay! " but it does not work for me but when I changed to 
 var razorpay: RazorpayCheckout!
It is working now
