### ISSUE TITLE
Module compiled with Swift 5.0 cannot be imported by the Swift 5.2.4 compiler

### ISSUE THREAD

**Issue by nitin-agam** [razorpay/razorpay-pod#99]
I'm getting this error while compiling the code:

Module compiled with Swift 5.0 cannot be imported by the Swift 5.2.4 compiler

Using 
Xcode: 11.5
Swift Version: 5

I've tried using pod with these versions
pod 'razorpay-pod', '~> 1.1.5'
pod 'razorpay-pod', '~> 1.1.1'

Please help me.

**Comment by ambujap94** [comment]
Please use as
if Swift 5.1+ 

pod 'razorpay-pod', '~> 1.1.5'

if Swift 5.0 

pod 'razorpay-pod', '~> 1.1.1'

You can refer our [integration document](https://razorpay.com/docs/payment-gateway/ios-integration/standard/) for further clarification
[CocoaPods document](https://cocoapods.org/pods/razorpay-pod) for reference.

**Comment by nitin-agam** [comment]
I have already tried both the version. But still facing the same issue.

**Comment by Mahesh160393** [comment]
Xcode Version : 11.6
Swift Version : 5

Same issue.

**Comment by Nautiyalsachin** [comment]
@Mahesh160393, Can you open **podfile.lock** and check the current **razorpay-pod** version and paste it here. It should be **more than 1.1.4.** If it's not then please use `pod update razorpay-pod`. This will only update the razorpay-pod to the latest version.

**Comment by Mahesh160393** [comment]
Thank you for your response @Nautiyalsachin 

Here is my pod lock version : 

In PODS :   - razorpay-pod (1.1.5)
In DEPENDENCIES:   - razorpay-pod

**Comment by Nautiyalsachin** [comment]
@Mahesh160393, try using RazorpayCheckout instead of Razorpay. Hope you've already have fixed this issue. 

For now closing this issue, feel free to either re-open or create a new issue if you have any additional queries.
